### ISSUE TITLE
iCloud support

### ISSUE THREAD

**Issue by jyounus** [JohnEstropia/CoreStore#1]
Hey,

This is looking great! I'm really looking forward to using this library. I'm currently working on an app and was going to use something called SugardRecords. I haven't started with my Core Data implementation yet and I came across CoreStore. Looks really interesting.

I wanted to ask if you have a rough time frame of iCloud support? How exactly are you imagining iCloud support to work? Will your library handle it all in the background or would code changes be required on the app side?

Thanks and great job! :)

**Comment by JohnEstropia** [comment]
Thanks for the feedback!

I'm prioritizing migrations right now so I can't give any guarantees on when iCloud support will be ready. (Although it's definitely in my TODO list)

One thing for sure is that when CoreStore does implement iCloud support, it will be through a different set of methods from the current API. So an app-side code update will most likely be required.

Other things I'm thinking about iCloud (from the top of my head):
- most likely to only support iCloud Drive (as Apple seem to be pushing in that direction)
- will definitely require migration utilities 
- will need a separate notification mechanism  to observe changes to the ubiquitous store

**Comment by jyounus** [comment]
When you say "most likely to only support iCloud Drive" does that mean the new iCloud stuff that they introduced with iOS8 (in other words, only support iOS8 and above)? It will be basically CoreData but stored/synced with the user's iCloud account? Or am I mixing something up here?

I'm really willing to go with this library over SugarRecords. I'm really hoping iCloud support won't be too long (definitely before the end of the year-ish). You think that's reasonable and that you'll have it done by then? I'd consider doing it myself and submit PRs but I'm really not that good (yet) lol.

**Comment by JohnEstropia** [comment]
>When you say "most likely to only support iCloud Drive" does that mean the new iCloud stuff that they introduced with iOS8

Yes. Basically only iOS 8 users that upgrade their account to iCloud Drive can use it.
You can get an idea here: https://support.apple.com/en-us/HT201104

>(in other words, only support iOS8 and above)?

CoreStore can't be used on iOS 7 to begin with. I made that decision considering the timing of iOS 9.

>I'm really hoping iCloud support won't be too long (definitely before the end of the year-ish)

Definitely shouldn't take that long :) Maybe in a couple of months, or shorter if someone else makes submits a pull request.

**Comment by jyounus** [comment]
Perfect. That works for me! Looking forward to the implementation! :D

Will be CoreStore in the meantime for 'offline' CoreData storage in my app. :)

**Comment by JohnEstropia** [comment]
Thanks!

**Comment by Shirk** [comment]
:+1: 
I'm holding out on a complete switch since some of my clients require iCloud sync for their data.
However I think iCloud-Drive will do just fine :smile:

**Comment by JohnEstropia** [comment]
Apologies to everyone waiting for iCloud support for a long time. I'm currently working on this as part of CoreStore 2, which will support custom stores aside from SQLite and In-Memory stores. I'll close this ticket but you can track the progress here https://github.com/JohnEstropia/CoreStore/issues/55.
