### ISSUE TITLE
Method calls are dispatched incorrectly if entity type is referenced as supertype

### ISSUE THREAD

**Issue by deville** [JohnEstropia/CoreStore#107]
Consider the following class hierarchy:

```swift
// abstract entity class
open class StorableEntity: NSManagedObject, ImportableUniqueObject
    // ...
    open class var uniqueIDKeyPath: String {
        fatalError("this has to be overridden")
    }
}

// concrete entity
@objc(Thing)
class Thing: StorableEntity {
    class var uniqueIDKeyPath: String {
        return "id"
    }

    @NSManaged var id: NSString
    @NSManaged var content: String?
}
```

Let's try to import a `Thing` now. The following code will work:
```swift
let entityType = Thing.self
let object = try transaction.importUniqueObject(Into(entityType), source: ["id": "1", "content": "some content"])
```

but the following will not:
```swift
let entityType: StorableEntity.Type = Thing.self
let object = try transaction.importUniqueObject(Into(entityType), source: ["id": "1", "content": "some content"])
```

`entityType` is now `StorableEntity.Type`. Since `importUniqueObject` method relies on generic parameter to determine which type to use for static method calls this means that all invocations will be dispatched to `StorableEntity` instead of `Thing`. Which in this concrete example means that the app will crash because `StorableEntity.uniqueIDKeyPath` is abstract.

Here's the project which reproduces this issue:
[CoreStoreImportCrasher.zip](https://github.com/JohnEstropia/CoreStore/files/516105/CoreStoreImportCrasher.zip)

**Comment by JohnEstropia** [comment]
Hi, thank you for the feedback.

I'm not sure if this is something to "fix". This is just how Swift generics works. If you really need dynamic behavior, `Into` clauses actually support that:
```swift
let object = try transaction.importUniqueObject(
    Into<StorableEntity>(Thing.self as AnyClass), 
    source: ["id": "1", "content": "some content"]
)
```
Use the initializer that accepts `AnyClass` argument. `From` clauses also support this.

**Comment by deville** [comment]
@JohnEstropia well, your example actually crashes as well. Have you tried running the test project?

> This is just how Swift generics works.

yes, that's why generics cannot be relied on for correct method dispatch. I created a pull request #108 which fixes this issue by calling type methods on `entityClass` from the `Into` object instead of  calling them on the generic type. I'm not sure, however, if similar fixes are needed elsewhere.

**Comment by JohnEstropia** [comment]
Thanks for the PR! I'll check your project when I get access to Xcode later. Your PR looks good though, I'll look for other places similar.

**Comment by JohnEstropia** [comment]
Merged your PR. Thanks again!

Will update the Swift 2.3 branch with the same fixes as well
