### ISSUE TITLE
Is it possible remove database from code?

### ISSUE THREAD

**Issue by avshiyanov** [JohnEstropia/CoreStore#114]
For example after each update of app I want delete previous DB

**Comment by JohnEstropia** [comment]
@avshiyanov You can simply delete the sqlite file before you initialize anything else. Which version of CoreStore are you using?

**Comment by avshiyanov** [comment]
@JohnEstropia I use swift3 branch

**Comment by JohnEstropia** [comment]
If so you can use the `SQLiteStore`'s `fileURL` property to pass to `FileManager.default.removeItem(at:)`:
```swift
let storage = SQLiteStore(...)
_ = try? FileManager.default.removeItem(at: storage.fileURL)

CoreStore.addStorage(storage, ...)
```
