### ISSUE TITLE
Fetch limit ?

### ISSUE THREAD

**Issue by ThibaultVlacich** [JohnEstropia/CoreStore#116]
Hello,

When doing a `CoreStore.fetchAll` request, I haven't found a way to put a limit to number of entries to fetch. Is there a way to do that ? Something like :
```swift
CoreStore.fetchAll(
    From(Article.self),
    Where("featured = 1"),
    OrderBy(.descending("date")),
    Limit(10)
)
```

With CoreData alone I was doing (Swift 2) :
```swift
let request = NSFetchRequest(entityName: "Articles")
request.fetchLimit = 10
```

**Comment by JoeMatt** [comment]
You would use Tweak parameter to modify the NSFetchRequest directly.
```
CoreStore.fetchAll(
    From(Article.self),
    Where("featured = 1"),
    OrderBy(.descending("date")),
    Tweak { (fetchRequest) -> Void in
         fetchRequest.fetchLimit = 10
    }
)

**Comment by ThibaultVlacich** [comment]
Thanks @JoeMatt!  I'm gonna take a look if maybe I can make a PR to add a convenient `Limit` fetch clause.

**Comment by JakeSteam** [comment]
Semi-resurrecting this, any chance it can be put into the readme? Having to search through closed issues to find out how to limit seems crazy!
