### ISSUE TITLE
Swift 3 NSFetchedResultsController

### ISSUE THREAD

**Issue by colinmorelli** [JohnEstropia/CoreStore#119]
Making this to track an effort on opening up `NSFetchedResultsController` for Swift 3. I took a stab at it tonight, but I'm guessing the reason it was commented out in the first place is the same reason I eventually gave up for now: Objective-C generics?

As an alternative (and yes, I acknowledge how hard you've worked to make this not the case), would you consider exposing the `NSManagedObjectContext` instances? I've actually found multiple use cases for having access to them and am starting to feel that, given the correct caveats all over the documentation, it could be useful to provide.

In any case, is there any way (as is) to use an NSFRC in Swift 3?

**Comment by JohnEstropia** [comment]
@colinmorelli Thanks for bringing this up! As you have suspected, I removed the NSFetchedResultsController factory methods because during the Swift 3 beta builds there was no way to cast Objective-C "generic" types to each other:

```swift
let request: NSFetchRequest<NSFetchRequestResult> = // ...

return CoreStoreFetchedResultsController(
    // ...
    fetchRequest: request // error: cannot cast from NSFetchRequest<NSFetchRequestResult> to NSFetchRequest<NSManagedObject>
)
```
Fortunately Swift 3 now allows inter-casting with `as!`. I'll try to recover the commented-out code and see how much we can still use

**Comment by JohnEstropia** [comment]
> As an alternative (and yes, I acknowledge how hard you've worked to make this not the case), would you consider exposing the NSManagedObjectContext instances? I've actually found multiple use cases for having access to them and am starting to feel that, given the correct caveats all over the documentation, it could be useful to provide.

Can you share these use cases? I'm trying out an architecture right now where the context can be accessed if needed, BUT I'd like it to be a last resort and if there are use cases where the context needs to be exposed I'd prefer that CoreStore has it's own abstraction over that.

**Comment by colinmorelli** [comment]
Sure - just in the recent past, I have wanted to:

- observe changes within an (unsaved) context to calculate a computed field
on my entities before saving
- use NSNotificationCenter to observe for changes to an entity type in a
specific context and update a view, without performing an initial fetch
- use other libraries, such as JSQDataSourcesKit, which might expect direct
access to a context

At least those first two can certainly be accomplished with core store
abstractions. But ultimately it's going to be almost impossible to play
nicely with other libraries without allowing access to the context. At
least the main and root ones.

As for the NSFRC - any thoughts?

**Comment by JohnEstropia** [comment]
@colinmorelli NSFetchedResultsController utilities are available again!
For usage samples, see
https://github.com/JohnEstropia/CoreStore/commit/33a5c123aabce25de84559f421a345316a77ba6d#diff-a64622bdb6bd86124110367af47fe690R251 for Objective-C,
or https://github.com/JohnEstropia/CoreStore/commit/33a5c123aabce25de84559f421a345316a77ba6d#diff-17dc834c37c9b798806970e232364293R41 for Swift 3.


As for API's to expose the internal NSManagedObjectContext, please wait for a new protocol in an upcoming version I am currently implementing.

**Comment by colinmorelli** [comment]
Awesome - new apis for NSFetchedResultsController working great 👍

**Comment by JohnEstropia** [comment]
@colinmorelli Check out https://github.com/JohnEstropia/CoreStore/commit/b230ed6400b2ca38533d597b9f514e0f0bfc7871#diff-dd90dc4a77a046f05e715c4c0ea209d2R40
The `FetchableSource` and `QueryableSource` exposes
```swift
func internalContext() -> NSManagedObjectContext
```
