### ISSUE TITLE
Upgrade to 2.1.3 - OrderBy failure

### ISSUE THREAD

**Issue by netbe** [JohnEstropia/CoreStore#121]
Hi,

I am upgrading our project to 2.1.3, and seeing some failures like:
```
❗ [CoreStore: Assertion Failure] DataStack+Observing.swift:90 monitorList
  ↪︎ An 'NSFetchedResultsController' requires a sort information. Specify from a 'OrderBy' clause or any custom 'FetchClause' that provides a sort descriptor.
```
Most of the time, I see it because the fetchClauses contains OrderBy() only without any argument. Specifying the order then works fine, but not leaving it out 

**Failed**

```[Where()]```

```[Where(), OrderBy()]```

**Worked**

```[Where(), OrderBy(.Descending(ManagedPhysician.Keys.fullName.rawValue))]```

I am just wondering why the init on OrderBy is then public if it cannot be used or in which case it can be used at all.

Thanks

**Comment by JohnEstropia** [comment]
@netbe For ListMonitor, the OrderBy is required to have at least one sort key. Few reasons I left the default initializers public:

- `fetchAll()`, `deleteAll()` also accepts `OrderBy` clauses, and are perfectly fine with empty sorting
-  `NSFetchRequest.predicate` and `NSFetchRequest.sortDescriptors` both accept `nil` and empty arrays. The effect of either is undocumented so I left a way to set both `nil` and their `Where()` and `OrderBy()` empty counterparts
- `Where()` and `OrderBy()` can be used to explicitly express that the predicate and sort order are intentionally empty.

**Comment by netbe** [comment]
@JohnEstropia thx for the explanation
