### ISSUE TITLE
Question: Can you clarify the difference between fetchExisting(T) and edit(T)

### ISSUE THREAD

**Issue by popwarfour** [JohnEstropia/CoreStore#124]
I'm currently running from swift3_develop

In both async and sync transaction classes the edit functions look to just be calling the fetchExisting behind the scenes anyway. Is there a difference between the two I'm not seeing?

Great library, looking forward to using this more moving forward!

**Comment by JohnEstropia** [comment]
@popwarfour Nothing, really. Just semantic naming:`edit()` adds nuance that this object can be edited. But that's entirely up to you.

**Comment by popwarfour** [comment]
figured as much, thanks

**Comment by rivera-ernesto** [comment]
I see that `edit` runs more checks.

Where `fetchExisting`:

```swift
    public static func fetchExisting<D: DynamicObject>(_ object: D) -> D? {
        
        return self.defaultStack.fetchExisting(object)
    }
```

`edit`:

```swift
    public override func edit<D: DynamicObject>(_ object: D?) -> D? {
        
        CoreStore.assert(
            !self.isCommitted,
            "Attempted to update an entity of type \(cs_typeName(object)) from an already committed \(cs_typeName(self))."
        )
        
        return super.edit(object)
    }

    public func edit<D: DynamicObject>(_ object: D?) -> D? {
        
        CoreStore.assert(
            self.isRunningInAllowedQueue(),
            "Attempted to update an entity of type \(cs_typeName(object)) outside its designated queue."
        )
        guard let object = object else {
            
            return nil
        }
        return self.context.fetchExisting(object)
    }
```

Any comment @JohnEstropia ?

**Comment by JohnEstropia** [comment]
Yes they do technically the same thing. The only difference is the semantic use, `edit()` being available only to transactions. Instances created with `edit()` are expected to be "edited" so extra checks are put in place for you for "just in case" scenarios. It is not available to read-only contexts (i.e. DataStack)

`fetchExisting()` on the other hand is mostly used for moving instances across main and background contexts. For this reason it is available under the same name to both read-only and read-write contexts.

Of course you can just use `fetchExisting()` everywhere if you wish. But `edit()` is there so you can take advantage of the expressiveness and safety.
