### ISSUE TITLE
GCD Kit not compatible with swift 3

### ISSUE THREAD

**Issue by jadslim313** [JohnEstropia/CoreStore#128]
I'm installing 'CoreStore' on cocoapods. I wish to only install CoreStore not GCD kit but it always comes with it. GCDKit does not work with swift 3 and is causing all kinds of errors, preventing the use of what seems to be a great framework.

**Comment by JohnEstropia** [comment]
@jadslim313 Hi, CoreStore's swift3_develop branch doesn't depend on GCDKit anymore (although GCDKit also has its own swift 3 branch) 
[Podspec](https://github.com/JohnEstropia/CoreStore/blob/swift3_develop/CoreStore.podspec)

You do need to specify the swift3_develop branch in your Podfile:
```ruby
pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'swift3_develop'
```

**Comment by JohnEstropia** [comment]
I'm closing this issue. If you have other problems feel free to reopen :)
