### ISSUE TITLE
How to sort by relationship? 

### ISSUE THREAD

**Issue by rslim087g** [JohnEstropia/CoreStore#132]
I have an entity Person, each person has many messages. I wish to sort my tableview based on the last message's timestamp per each Person. Essentially, accomplish something like this . 
           let People: ListMonitor<Person> = {
        
        
              return Static.datastack.monitorSectionedList(
            
                   From<Person>(),
                   SectionBy(#keyPath(Person.section)),
                   Where("messages.@count > 0"),
                   OrderBy(.descending(#keyPath(Person.messages.last.timestamp))) <--------
            
        )
        
    }()

**Comment by JohnEstropia** [comment]
Unfortunately, Core Data doesn't support sorting lists with relationships. My suggestion is to add a `messageCount` attribute in the `Person` entity which you update whenever a message is added to  a person. You can then use that attribute to sort.

**Comment by rslim087g** [comment]
Thank you John, just making sure I wasn't missing out on a feature. I guess that should work !
