### ISSUE TITLE
what is the location of sqlite file?

### ISSUE THREAD

**Issue by rslim087g** [JohnEstropia/CoreStore#134]
I need the location of the sqlite file for easier debugging. I'm trying to have a visual representation of what is inside my server to better understand what is going on. is there a function you guys have to obtain it?

**Comment by JohnEstropia** [comment]
@rslim087g The `SQLiteStorage` instance you pass to `DataStack.addStorage(...)` has a `fileURL` property you can use to locate the actual file.
