### ISSUE TITLE
Importing large datasets

### ISSUE THREAD

**Issue by terenzeyuen** [JohnEstropia/CoreStore#135]
We noticed whenever we trigger commit with large imports (30k record), UI thread stalls for a few seconds. Is this normal? @JohnEstropia

**Comment by JohnEstropia** [comment]
Do you use ListMonitors? Saving objects will trigger updates on monitors, which notifies the UI on the main thread. So if you save a lot of objects at once those will have noticeable effects on the UI.

My suggestion is to save your 30k records into chunks. Say, one `beginAsynchronous` for each 1000 items.

**Comment by terenzeyuen** [comment]
Thanks !
