### ISSUE TITLE
Entity classes not found from frameworks

### ISSUE THREAD

**Issue by deanWombourne** [JohnEstropia/CoreStore#137]
Hi,

If I make a framework which uses CoreStore, then the entity classes aren't being found.The exception is being thrown from `DataStack.swift:484` on the swift3_develop branch (commit 23df460c3587503b61dc608380a076195b7434bf according to my pod file.lock)

Playing around in the debugger, I get this:

```
(lldb) po managedObjectClassName
"TaskTimerModel.ClientEntity"

(lldb) po NSClassFromString(managedObjectClassName)
nil

(lldb) po NSClassFromString("ClientEntity")
nil
```

However, I can get it to find the class if I go to my framework bundle directly, and remove the module prefix from the class.
```
(lldb) po Bundle.allFrameworks[29]
( this is my framework containing the entity classes)

(lldb) po Bundle.allFrameworks[29].classNamed("ClientEntity")
▿ Optional<AnyObject.Type>
  - some : TaskTimerModel.ClientEntity

(lldb) po Bundle.allFrameworks[29].classNamed("TaskTimerModel.ClientEntity")
nil
```

Not sure how to fix this reliably, or where else in the library this issue might become apparent, sorry!

**Comment by deanWombourne** [comment]
Hmmm, just to make this more interesting, I backed up one commit to where the classes were all in the sam module, and I got exactly the same error.

I fixed it by getting Xcode to create the managed object subclasses automatically instead of manually. Then, the managedObjectClassName didn't contain the module prexfix, and NSClassFromString worked. I have absolutely no idea why.

**Comment by JohnEstropia** [comment]
Hi, I am not sure you can get the same behavior from the llvm debugger as the modules loaded there are different from the ones in the swift file. Have you tried marking your classes as `@objc` or `public open`?

**Comment by deanWombourne** [comment]
They're already `@objc public` :(

However, it seems to work if I make them don't select anything (i.e. use the default Global namespace) in the Module dropdown in Xcode. The sum total of the change to xcdatamodel/contents is this:

```
-    <entity name="ClientEntity" representedClassName="ClientEntity" syncable="YES">
+    <entity name="ClientEntity" representedClassName=".ClientEntity" syncable="YES">
```

First line works (i.e. class name is just `ClientEntity`) but the second one fails (class name becomes `TaskTimer.ClientEntity`, which isn't found).

I'm fine leaving them in the global namespace for this app and it's working great (ps I'm loving CoreStore ;) but it does mean that if I wanted to build a library with CoreStore I might run into trouble.

I'll keep playing around and see what other class I can find.

**Comment by JohnEstropia** [comment]
You can also try to declare the module name explicitly in your xcdatamodel instead of `Current Product Module`.

I'll close this issue as this seems to be more of a model configuration mismatch than a CoreStore problem. Thanks for the feedback!
