### ISSUE TITLE
Misleading exception message for missing managed object subclasses

### ISSUE THREAD

**Issue by deanWombourne** [JohnEstropia/CoreStore#138]
If corestore can't find the managed object subclass, an exception is thrown:

```
❗ [CoreStore: Assertion Failure] DataStack.swift:478 createPersistentStoreFromStorage(_:finalURL:finalStoreOptions:)
  ↪︎ The class 'Swift.String' for the entity <ClientEntity> does not exist. Check if the subclass type and module name are properly configured.
```

This should really be:
```
❗ [CoreStore: Assertion Failure] DataStack.swift:478 createPersistentStoreFromStorage(_:finalURL:finalStoreOptions:)
  ↪︎ The class 'TaskTimer.ClientEntity' for the entity <ClientEntity> does not exist. Check if the subclass type and module name are properly configured.
```

`Swift.String` is the class of the _name_ of the missing class - the missing class is really `TaskTimer.ClientEntity`

**Comment by JohnEstropia** [comment]
Thanks. That is weird. Must be a Swift 3 side effect.

**Comment by deanWombourne** [comment]
Yes, I've had odd things like this moving to swift 3 as well :/ I _think_ it's using the generic version of `cs_typeName` instead of the `String?` one when you pass in a `String`, but I can't say why, or predict when it happens yet. I guess practice makes perfect :)

**Comment by JohnEstropia** [comment]
@deanWombourne I think your PR should resolve this. I see you reopened the issue, have you found cases where the wrong overload still gets called?

**Comment by deanWombourne** [comment]
Nope - I pressed the wrong button submitting my last comment and closed it by mistake, so I reopened it. I wasn't sure when yo closed issues - fixed in master vs. released so I left it open for you to close when you want :) It's definitely fixed for me.
