### ISSUE TITLE
Supporting other cloud services

### ISSUE THREAD

**Issue by tosbaha** [JohnEstropia/CoreStore#140]
Hi,
Besides iCloud, is it possible to use other cloud services like Dropbox,Google or our own server(JSON result) to sync the core data? Where should I look in the code to support syncing with my own server? If there is a way to use protocols or some kind of sub classing it will be better than changing multiple places. I think it could be super cool to add some kind of protocol so that people can add plugins to CoreStore to support different cloud services.

**Comment by JohnEstropia** [comment]
There is currently no built-in mechanism for file syncing in CoreStore so you will have to implement your own if you are using services like Dropbox or Google, but to be honest that sounds difficult ([Ensembles](http://www.ensembles.io/) is good at this, but I doubt there will be a way to mix it with CoreStore)

If you have your own server, however, you can use the `ImportableObject` and `ImportableUniqueObject` objects to map your JSON responses. See https://github.com/JohnEstropia/CoreStore#importing-data

**Comment by tosbaha** [comment]
Thanks for your quick response. Yes I have my own server and `ImportableObject` and `ImportableUniqueObject` seem like a good starting point. 👍
