### ISSUE TITLE
Discard Changes/Refresh Object

### ISSUE THREAD

**Issue by mitchclay** [JohnEstropia/CoreStore#144]
I don't see any examples and don't see anything in the documentation about how to discard changes.  Like I have an object that I use to fill out a form of a screen, I will assign some of the entered data that could be further modified on another screen but then the user selects a Cancel button, it should discard the changes and pull the original object from the persistent store.

How do I do that with this?

**Comment by JohnEstropia** [comment]
Hi, when you call `commit()` on any transaction, your changes will be saved and unless you have other flagging mechanisms in your app those changes cannot be `discarded`. If you want to hold temporary changes before committing them, you can use the `dataStack.beginUnsafe()` transaction variant, which creates a transaction that can freely make changes and make commits on any queue.
