### ISSUE TITLE
Question about AddStorageAndWait. 

### ISSUE THREAD

**Issue by rslim087g** [JohnEstropia/CoreStore#147]
I took reference to the example code creating a datastack like so. 

        struct Static {
    
       static let datastack: DataStack = {
       let datastack = DataStack(modelName: "Persistence")
       try! datastack.addStorageAndWait((SQLiteStore(fileName: "Persistence",     localStorageOptions: .recreateStoreOnModelMismatch)))
       return datastack
         }()
        }
However my concern is that I'm using Static.datastack everywhere to reference the datastack. Wouldn't it keep adding a Storage every single time I reference it somewhere. For example every time I would call Static.datastack.beginAsynchronous, which is called dozens of times in the lifetime of the app.

**Comment by rslim087g** [comment]
I guess making it a static variables ensures it uses the same one over and over. ?

**Comment by JohnEstropia** [comment]
This syntax uses an inline closure call to initialize the stack, which gets called once the first time it is called. I think you are confusing it with computed variables. Note the difference in the syntax:
```swift
var something: DataStack = {
    // ...
}() // This is a function CALL; runs once
```
```swift
var something: DataStack {
    // ...
} // This is a function BODY; run everytime
```

**Comment by rslim087g** [comment]
thanks for clearing that up!
