### ISSUE TITLE
SynchronousDataTransaction commit() not marked @discardableResult

### ISSUE THREAD

**Issue by avaroam** [JohnEstropia/CoreStore#148]
Just thought I'd mention that the `commit()` method of `SynchronousDataTransaction` is not marked with `@discardableResult`, meaning it must currently be used like this:

```
_ = transaction.commit()
```

I'm not sure if this is intentional, but it seems like something that would often not be used, and in the read me it is used without `_ =`

Also, same is true of `commitAndWait()`

**Comment by JohnEstropia** [comment]
This was intentional because the result should generally be handled. Incidentally `beginSynchronous()` was made `@discardableResult` so that you can handle the result in one place. Maybe interchange the discardableResult attribute on those two methods?

**Comment by avaroam** [comment]
That makes sense! Having no discardable result on `commit()` makes it consistent with async transactions. Just thought I'd mention it because it's written without `_ =` in the README.

Out of curiosity, what would be the usual way to handle the `SaveResult`? What would be a use case for `hasChanges`, and is it really worth checking the `CoreStoreError` for all transactions? What would be a suitable course of action if an error did occur?

**Comment by JohnEstropia** [comment]
Since transactions produce `.success` when there are no changes, the `hasChanges` is used when you need distinguish that case. This is useful in cases like data imports.

Of course it is up to you and your app if you need to handle these results or not. The syntax just makes it clear that you explicitly chose to do it.

**Comment by avaroam** [comment]
Nice. I've just been ignoring the result in most cases (if not all), but I can definitely see where it could be useful. Thanks for the insight!
