### ISSUE TITLE
Importing data

### ISSUE THREAD

**Issue by ro22e0** [JohnEstropia/CoreStore#152]
Does CoreStore support [UserInfo Keys](https://github.com/magicalpanda/MagicalRecord/blob/master/Docs/Importing-Data.md#attributes) like MagicalRecord ?

**Comment by JohnEstropia** [comment]
Sorry, not *yet*. This is actually currently being prototyped but there is no release schedule yet.

**Comment by DimaAvvakumov** [comment]
Hi! Thanks for awesome library.

One question - this feature still in prototy state?

**Comment by JohnEstropia** [comment]
@DimaAvvakumov Ah, I sort of abandoned this as I didn't like the complete magic string-dependency. Even released an architecture to get rid of `xcdatamodel`s completely ([CoreStoreObject](https://github.com/JohnEstropia/CoreStore#type-safe-corestoreobjects).

Let me know if there is a significant benefit for your use-case with userInfo keys instead of the current `ImportableObject` method.

**Comment by DimaAvvakumov** [comment]
Thank you for answer. UserInfo keys is not my primary goal. I want to custom mapping keys while importing object from json.

For example: 
*json*
```{
  "id": 1,
  "FullName": "John Dow"
}
```

*entity*
```class User {
  var id: Int = 0
  var name: String?
}
```

How can i import this?

**Comment by JohnEstropia** [comment]
@DimaAvvakumov Check out the `ImportableUniqueObject` protocol:
https://github.com/JohnEstropia/CoreStore#importing-data

Simple example:
```swift
class User: NSManagedObject, ImportableUniqueObject {
    @NSManaged var id: Int
    @NSManaged var name: String?

    // MARK: ImportableUniqueObject
    typealias ImportSource = [String: Any]
    typealias UniqueIDType: Int

    class var uniqueIDKeyPath: String {
        return #keyPath(User.id) 
    }
    class func uniqueID(from source: ImportSource, in transaction: BaseDataTransaction) throws -> Int? {
        return source["id"] as? Int
    }
    func update(from source: ImportSource, in transaction: BaseDataTransaction) throws {
        self.name = source["name"] as? String
    }
}
```

You can then import your object via transactions:
```swift
CoreStore.perform(
    asynchronous: { (transaction) -> Void in
        let json: [String: Any] = // ...
        try! transaction.importUniqueObjects(
            Into<User>(),
            sourceArray: (json["users"] as? [User.ImportType]) // [[String: Any]]
        )
        // ...
    },
    completion: { _ in }
)
```

**Comment by DimaAvvakumov** [comment]
Thank you, I'll deal with this.

**Comment by JohnEstropia** [comment]
Sounds tough! 😆 
Feel free to ask anything!

**Comment by Pratik-Sodha** [comment]
Thank you for awesome CoreData Wrapper. 

I have situation in which i have to store pre-fill master data. Sync at app launch event. I have array of Model. 

**For example : **

```
class ToyStory {
    var id: Int = 0
    var name: String?
    
    init(id : Int, name : String) {
        self.id = id
        self.name = name
    }
}

let modelsArray : [ToyStory] = [
    ToyStory(id: 1, name: "Sherrif Woody"),
    ToyStory(id: 1, name: "Buzz"),
    ToyStory(id: 1, name: "Andy"),
    ToyStory(id: 1, name: "Rex")
]
```

Thank you in advance :)
