### ISSUE TITLE
Question: Method to check it database exists

### ISSUE THREAD

**Issue by mrichtsfeld** [JohnEstropia/CoreStore#163]
Hi @JohnEstropia,

Is there any way to find out if a database already exists before adding it? E.g. I need to do some pre-setup stuff if the user had no database. 

Thanks a lot

**Comment by JohnEstropia** [comment]
@mrichtsfeld If you just need to check if the file exists, you can use `SQLiteStore` to query `FileManager`:
```swift
let storage = SQLiteStore(fileName: "my.sqlite")
if FileManager.default.fileExists(atPath: storage.fileURL.path) {
    // ... pre setup stuff
}
``

**Comment by mrichtsfeld** [comment]
@JohnEstropia that works perfect for me. Thanks for the hint.

**Comment by HristiyanZahariev** [comment]
What does pre setup stuff mean? How am I able to use this sqlite database?

**Comment by JohnEstropia** [comment]
@HristiyanZahariev You can initialize an SQLiteStore with your own file URL:
```swift
CoreStore.defaultStack = DataStack(
    xcodeModelName: "Model", // your xcdatamodeld name
    bundle: Bundle(for: type(of: self))
)
try CoreStore.addStorageAndWait(
    SQLiteStore(
        fileURL: yourFileURL // here
    )
)
```
