### ISSUE TITLE
CoreStore query multiple entities

### ISSUE THREAD

**Issue by martheli** [JohnEstropia/CoreStore#166]
I have read over the readme but I have not seen any examples of how to pull data from two entities if there is a relationship. For example if I had one entity that was Manager and one that was Employee. I wanted the result output to show the employee and the employee's manager. Is this type of query supported in CoreStore?

**Comment by JohnEstropia** [comment]
I'm not sure I understood your question. You can fetch the employee and then access the manager for that employee. So if you have these entities:
```swift
class Employee: NSManagedObject {
    // ...
    @NSManaged var manager: Manager?
}
class Manager: NSManagedObject {
    // ...
    @NSManaged var employee: Employee?
}
```
You can fetch the employee
```
let employee = CoreStore.fetchOne(
    From<Employee>(),
    Where( ... ) // some condition
)
```
and then access the manager
```swift
let manager = employee.manager
```

Does this answer your question?

**Comment by martheli** [comment]
Ok yes that does answer it. Do you need to set up the entities as classes like you show above for it to work or can I use the xcmappingmodel file to set up the entities only?

**Comment by JohnEstropia** [comment]
You can create the xcdatamodeld file and let Xcode automatically generate the class code for you.
