### ISSUE TITLE
Error with param of type Date since 4.0.2

### ISSUE THREAD

**Issue by ThibaultVlacich** [JohnEstropia/CoreStore#170]
I have this error since 4.0.2:

> Cannot invoke value of type `ValueContainer<Article>.Required<Date>.Type` with argument list `(String)`

Here's the related part of the code:

```swift
import CoreStore

class Article: CoreStoreObject {
    
    let date = Value.Required<Date>("date")

}
```

Was working perfectly before. I can't explain why is that by looking at the changes.

**Comment by JohnEstropia** [comment]
The fix here https://github.com/JohnEstropia/CoreStore/issues/169 included a change that removed non-intuitive defaults for Date, URL, UUID, etc. For these types you'll need to provide a `default` argument:
```swift
let date = Value.Required<Date>("date", default: Date.distantPast)
```
Or you can just use `Value.Optional<Date>`.

**Comment by ThibaultVlacich** [comment]
Oh, so it's linked to this fix. I thought it was working with 4.0.1 but I might be wrong, that's why I didn't make the connection.
