### ISSUE TITLE
CoreStore won't compile in Swift 3.2 and Swift 4

### ISSUE THREAD

**Issue by Plnda** [JohnEstropia/CoreStore#171]
/Users/Jason/git/telegraaf-ios/Pods/CoreStore/Sources/CoreStore+CustomDebugStringConvertible.swift:1202:9: Switch must be exhaustive

**Comment by JohnEstropia** [comment]
Currently working on Swift 3.2, thanks!

**Comment by athei** [comment]
Can you look into the compile errors for Swift4, too? These are only few and seem to be easy to resolve. SWIFT_VERSION is set to 4.0 for the CoreStore target, when using cocoapods for some reason.

**Comment by Plnda** [comment]
@athei the bug also happens on swift 4.0

**Comment by JohnEstropia** [comment]
@athei Yup I already fixed the easy compiler issues. The last issue is not a compiler error per-se, but a compiler crash.

**Comment by JohnEstropia** [comment]
I have a workaround for Swift 3.2 on the `prototype/Swift_3_2` branch. If anyone is interested feel free to play around. Will merge on the main branches when Xcode 9 leaves beta.

**Comment by Plnda** [comment]
@JohnEstropia how do i reference this in cocoa pods :)

**Comment by JohnEstropia** [comment]
Cocoapods
```ruby
pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'prototype/Swift_3_2'
```

Carthage
```ruby
github "JohnEstropia/CoreStore" "prototype/Swift_3_2"
```

**Comment by JohnEstropia** [comment]
## Swift 4

Podfile
```ruby
pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'prototype/Swift_4_0'
```

Cartfile
```ruby
github "JohnEstropia/CoreStore" "prototype/Swift_4_0"
```
