### ISSUE TITLE
How to fetch objects in backgound?

### ISSUE THREAD

**Issue by sidlatau** [JohnEstropia/CoreStore#173]
I am trying to fetch data in background, and use fetched data in main thread, but when I try to access managed objects properties app crashes. Problem  for this I think is that background context is destroyed when transaction finishes. Is it possible to change managed objects context to main somehow (simmilar to ```transaction.edit(object)``` functionality)?  

```
DataStack.beginAsynchronous { transaction in
               let data = transaction.fetchAll(
                 From<Object>(),
                 Where(...)
                ) ?? []
               transaction.commit { _ in
                     callback(data)
               }
}
```

**Comment by JohnEstropia** [comment]
Yes, you need to fetch it again from your datastack:
```swift
callback(DataStack.fetchExisting(data)!)
```

**Comment by sidlatau** [comment]
That's exactly what I needed. Thanks for quick response.
