### ISSUE TITLE
Compile error in Release Build (Swift 4.0)

### ISSUE THREAD

**Issue by athei** [JohnEstropia/CoreStore#176]
When compiling CoreStore Swift 4.0 branch as release build I get the following error:
`CoreStore/Sources/DataStack.swift:44:80: Static let 'applicationName' is internal and cannot be referenced from a default argument value`

This makes sense as with Swift 4.0 you cannot use variables of a more restricted visibility as default arguments. You need to wrap it with a public accessor. I don't know why this does not come up in a debug build.

**Comment by JohnEstropia** [comment]
I missed that. Thanks for raising this

**Comment by JohnEstropia** [comment]
Fixed on the `prototype/Swift_4_0` branch.
