### ISSUE TITLE
Little leak when running this code, would you know why this happens?

### ISSUE THREAD

**Issue by Plnda** [JohnEstropia/CoreStore#178]
do {

            try CoreStore.perform(synchronous: { transaction -> Void in
            // Delete the current user data
                transaction.deleteAll(From<User>())

                var avatarString = tripleAUser.avatarURI
                if !avatarString.contains("https:") {
                avatarString = "https:" + avatarString
                }

                // Create a new user
                let user = transaction.create(Into<User>())
                user.identifier = Int64(tripleAUser.id)
                user.name = tripleAUser.name
                user.email = tripleAUser.email
                user.avatar = avatarString
            })
        } catch _ {
            print("error")
        }

**Comment by JohnEstropia** [comment]
@Plnda I can't tell with just this code, can you give other info? Have you found through Instruments what objects/types are getting leaked?

**Comment by JohnEstropia** [comment]
@Plnda Have you resolved this issue? I will close this issue as irreproducible as I can't see this happening on the demo app.
