### ISSUE TITLE
Fetch all results starting with letter A

### ISSUE THREAD

**Issue by matuslittva** [JohnEstropia/CoreStore#179]
Hello i want to write query to select all results starting with particular letter, but this where clause is not working:

Where("name like 'A%'")

What is the problem?

**Comment by JohnEstropia** [comment]
@matuslittva`Where` clauses use `NSPredicate`s internally, so you need to write
```swift
Where("%K BEGINSWITH %@", "name", "A")
```

There's a good cheat sheet here: http://nshipster.com/nspredicate/
(Under "String Comparisons")

**Comment by matuslittva** [comment]
@JohnEstropia thank you so much
