### ISSUE TITLE
Does it support Multi-thread?

### ISSUE THREAD

**Issue by ondev** [JohnEstropia/CoreStore#180]

**Comment by JohnEstropia** [comment]
@ondev That depends what you mean by "it" and "multi-thread".
CoreStore runs on top of Core Data, so all threading support offered by Core Data is inherited by Core Store. This includes reading and writing objects from a background thread.

On the other hand, CoreStore will enforce that object properties are accessed only on the queue they correspond to. In that sense, an object is not "multi-thread". For example, an object read from the main thread cannot be manipulated directly from a transaction queue. There are utilities to get the correct object for the correct queue (`transaction.edit(_:)`, `transaction.fetchExisting(_:)`, etc).

**Comment by ondev** [comment]
Thanks your reply.
