### ISSUE TITLE
Xcode9 beta 5 - NSManagedObjectModel no longer has an optional init (Swift3.2)

### ISSUE THREAD

**Issue by akac** [JohnEstropia/CoreStore#182]
Xcode 9 Beta 5 - CoreStore test for optional init now breaks the building. I just changed it in my check out, but just letting you know :)

**Comment by JohnEstropia** [comment]
Thanks, will check it out

**Comment by JohnEstropia** [comment]
Fixed!

**Comment by akac** [comment]
And…beta 6 changes it back. Fun times.

**Comment by JohnEstropia** [comment]
Wow 😂  I'll look into it

**Comment by JohnEstropia** [comment]
Fixed in the latest Swift 4 branch
