### ISSUE TITLE
Compile error with Xcode9.0 beta5

### ISSUE THREAD

**Issue by laeroah** [JohnEstropia/CoreStore#184]
Tried to compile CoreStore using xcode9.0 beta5 and got a compile error in file `DataStack+Migration.swift`: `private func computeMigrationFromStorage<T: LocalStorage>(_ storage: T, metadata: [String: Any]) -> [(sourceModel: NSManagedObjectModel, destinationModel: NSManagedObjectModel, mappingModel: NSMappingModel, migrationType: MigrationType)]?`

![screen shot 2017-08-09 at 12 17 54 pm](https://user-images.githubusercontent.com/1928509/29132209-7eced7f4-7cfd-11e7-8cb8-68786f4f9cc9.png)

A PR created: https://github.com/JohnEstropia/CoreStore/pull/185

**Comment by sidmani** [comment]
I'm using the swift-4 branch and I don't get any compile errors on Xcode 9 beta 5. Which branch are you on?

**Comment by laeroah** [comment]
hey @sidmani 
I'm using `prototype/Swift_4_0` branch. Which branch are you on?

**Comment by sidmani** [comment]
@laeroah `prototype/Swift_4_0` as well. I'm installing via cocoapods like so:  
 `pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'prototype/Swift_4_0'`

**Comment by laeroah** [comment]
yeah, that's exactly how I installed too. I just downloaded the CoreStore source code and it seems to be compiling fine. I guess the problem might be on my side. May I see your podfile please?

**Comment by sidmani** [comment]
That's the only relevant part- the rest is just other pods for my project. It doesn't have any other configuration (except `use_frameworks!`)

**Comment by JohnEstropia** [comment]
@laeroah 
That is weird. Looking at the PR, there must be something else going on as either code should work on both Swift 3.2 and 4.0.

Some hunches:
- Do you have multiple Swift toolchains installed?
- Do you have multiple Xcode versions open at the same time?
- Do you reopen your project when git-switching between the 3.2 and 4.0 branches?

**Comment by JohnEstropia** [comment]
@laeroah I think I found the cause for this error. Are you using the CoreStore Swift 4 branch and building it into your project as a Swift 3.2?
I reproduced this problem when I used the Swift 4 branch but my podfile includes:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end
```
which builds it as Swift 3.2.

**Comment by laeroah** [comment]
hey, I didn't add config.build_settings['SWIFT_VERSION'] = '3.2' in my Podfile, but it is very possible that this is the cause. There's no issue if I start a new project and import CoreStore, so the problem must be on my side. I'm going to make sure Xcode is using swift4 instead of 3.2 and try it again.
Thank you for looking into it! much appreciated!

**Comment by JohnEstropia** [comment]
@laeroah Have you confirmed the cause on your side? I have already resolved this on my side by adding a conditional check (something like `if target == CoreStore, swift_version = 4`), but I want to make sure first if this is the same cause as yours.

**Comment by laeroah** [comment]
sry for delay. Yeah, I can confirm the issue is on my side. Thanks!

**Comment by ruslanskorb** [comment]
@laeroah Please open **Pods** project in Xcode, select **CoreStore** target and check **Swift Language Version**. Which value is selected?
