### ISSUE TITLE
WatchOS 2 support

### ISSUE THREAD

**Issue by tosbaha** [JohnEstropia/CoreStore#19]
I tried to use CoreStore with WatchOS extension however it doesn't integrate with Cocoapods. Cocoapods complain that 

```[!] The platform of the target `Myapp WatchKit Extension` (watchOS 2.0) is not compatible with `CoreStore (1.3.1)`, which does not support `watchos`.```

 I also tried to integrate as git submobule  but this time XCode compained that 

```Target 'CoreStore' of project 'CoreStore' was rejected as an implicit dependency for 'CoreStore.framework' because it doesn't contain platform 'watchsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'```

 I will appreciate if you can add WatchOS 2 support. Thanks.

**Comment by JohnEstropia** [comment]
@tosbaha Thanks for the feedback!
I pushed a compiling watchOS target to the develop branch. Can you try if it works for you? I'll merge it to the main branch and to cocoapods if everything goes well :)

**Comment by tosbaha** [comment]
Thanks @JohnEstropia I am sorry but for couple of days, I will be so busy and won't have time to test your fixes. I am sure they are working. I can't wait to try it on my project when you roll out cocoapods. Since I am lazy :)

**Comment by JohnEstropia** [comment]
@tosbaha It's ok, I'll upload it to cocoapods later in the day. Feel free to report any problems anytime!
