### ISSUE TITLE
Cannot compile demo project

### ISSUE THREAD

**Issue by rsardek** [JohnEstropia/CoreStore#192]
I cannot compile the demo project. I am running Xcode 8.3.2.

<img width="1389" alt="screen shot 2017-08-16 at 22 05 07" src="https://user-images.githubusercontent.com/965979/29383070-2c02b6d0-82cf-11e7-9ec4-f8309a8e397e.png">

**Comment by JohnEstropia** [comment]
Ah, thanks. `Value.Required` now requires an `initial:` argument and forgot to update the demo app.
