### ISSUE TITLE
NSManagedObjectModel initializer is failable in Xcode9 beta 6

### ISSUE THREAD

**Issue by Arasthel** [JohnEstropia/CoreStore#193]
In Xcode9 beta 6, all initializers - except the default one - of `NSManagedObjectModel` are failable. That creates a bug on [XcodeDataModelSchema.swift L171](https://github.com/JohnEstropia/CoreStore/blob/75e14fbbed7f6e11ea13e5e649a44caa2589c70a/Sources/XcodeDataModelSchema.swift#L171) on the `prototype/Swift_4_0` branch.

Maybe it can be fixed by reverting 74c6461?

**Comment by JohnEstropia** [comment]
Thanks. I just pushed the fix to the Swift 4 branch.
