### ISSUE TITLE
Compiler error with XCode beta6 in swift3_2 branch

### ISSUE THREAD

**Issue by laeroah** [JohnEstropia/CoreStore#194]
<img width="1247" alt="screen shot 2017-08-23 at 3 05 28 pm" src="https://user-images.githubusercontent.com/1928509/29634088-a12b9408-8816-11e7-8567-17850c141a99.png">

`NSManagedObjectModel` constructor `convenience init?(contentsOf url: URL)` returns an optional value but the function is expecting a nonoptional value. 
It seems that Xcode9 beta5 wasn't picking up this error for some reason. Xcode8 compiler will complain as expected. 

Looks like the old version had the unwrapping, but was removed in new version:
```
    public func rawModel() -> NSManagedObjectModel {
    
        if let cachedRawModel = self.cachedRawModel {
            
            return cachedRawModel
        }
        if let rawModel = NSManagedObjectModel(contentsOf: self.modelVersionFileURL) {
            
            self.cachedRawModel = rawModel
            return rawModel
        }
        CoreStore.abort("Could not create an \(cs_typeName(NSManagedObjectModel.self)) from the model at URL \"\(self.modelVersionFileURL)\".")
    }
```

**Comment by JohnEstropia** [comment]
Ah, I fixed this in the Swift 4 branch completely misunderstanding this was a Swift 4 change and not an iOS 11 change. Sorry about that. Will push the fix for the 3.2 branch as well.

**Comment by laeroah** [comment]
Thanks!

**Comment by JohnEstropia** [comment]
Fixed in the `prototype/Swift_3_2` branch as well. Thanks!
