### ISSUE TITLE
What am I missing in regards to ImportableUniqueObjects, to avoid it inserting a new row every time?

### ISSUE THREAD

**Issue by JakeSteam** [JohnEstropia/CoreStore#195]
So, I have a pretty simple database, with 5-6 tables that need to sync with remote JSON data. They all use `id` (Int64) as a primary key. 

As the later versions of CoreStore permit using the `.xcdatamodeld` directly, I opted for that method to avoid duplicating schemas. As such, I'm extending my model classes to obey the `ImportableUniqueObject` protocol. Inserting, querying etc all works fine, the only issue is with update vs insert.

I'm very much a novice Swift developer, so there's likely something very obvious I'm missing. Perhaps extensions can't be utilised in this manner?

**Expected behaviour**: If a row already exists for that `id`, the values for that row are updated. If not, a new row is inserted.
**Observed behaviour**: A new row is always inserted, regardless of whether the `id` is in use already.

```
extension Website: ImportableUniqueObject {
    public typealias ImportSource = [String: Any]
    public typealias UniqueIDType = Int64
    public class var uniqueIDKeyPath: String {
        return #keyPath(Website.id)
    }
    public var uniqueIDValue: Int64 {
        get { return self.id }
        set { self.id = newValue }
    }
    public class func uniqueID(from source: ImportSource, in transaction: BaseDataTransaction) throws -> Int64? {
        return Int64(source["id"] as! String)
    }
    public func update(from source: ImportSource, in transaction: BaseDataTransaction) throws {
        print("Saving website with ID \(source["id"] as! String)")
        self.id = Int64(source["id"] as! String)!
        self.name = source["name"] as? String
        self.hex = source["hex"] as? String
        self.last_updated = getDate(source["updated"] as! String)
    }
}
```

This is called via `transaction.importObjects(Into<Website>(), sourceArray: jsonArray)`, where `jsonArray` is a JSON array containing something similar to https://pastebin.com/4707LPKk

**Comment by JohnEstropia** [comment]
Hi, can you show your import code?

**Comment by JakeSteam** [comment]
Replied before I could even edit post to include it!

Just calling `transaction.importObjects(Into<Website>(), sourceArray: jsonArray)`, where `jsonArray` is a JSON array containing something similar to https://pastebin.com/4707LPKk

**Comment by JohnEstropia** [comment]
Ah, try to use `importUniqueObjects()` instead

**Comment by JakeSteam** [comment]
Perfect! Knew it would be something super simple. Might want to update the documentation to mention it, thanks so much for your extremely swift help!

**Comment by JohnEstropia** [comment]
Thanks, will mention in the docs (and maybe dump a runtime warning)
