### ISSUE TITLE
List Monitor didUpdateObject method not called

### ISSUE THREAD

**Issue by tomasgibas** [JohnEstropia/CoreStore#20]
I'm using ListMonitor object to set data in table view. ListObjectObserver methods are called fine, only didUpdateObject method is never called when I update some of the object in ListMonitor. I'm ImportableUnique object to update, create and delete objects.

**Comment by JohnEstropia** [comment]
@tomasgibas Thanks for the report! Can you give me more details on the following?
- device's iOS version
- if you're using sections or not
- specific order of inserts/updates/deletes that triggers the bug
- any hints you may find relevant

We're trying to find all edge cases of NSFetchResultsController's nasty bugs that were introduced on XCode 7.

Related discussions:
https://github.com/JohnEstropia/CoreStore/issues/12
https://forums.developer.apple.com/thread/4999

**Comment by JohnEstropia** [comment]
@tomasgibas Can you check if the master branch fixes the problem for you?

**Comment by tomasgibas** [comment]
Using iOS 9.1 and 8.4
Yes, it is with sections,
I'm fetching data from server and save it to persistent store, there is when I expect method to be called

**Comment by tomasgibas** [comment]
At first look, it seems working. Great! Thank you.

**Comment by JohnEstropia** [comment]
@tomasgibas That's great! I'll close this ticket but feel free to report any other issues you find. Thanks!
