### ISSUE TITLE
Pod lib try not compiling

### ISSUE THREAD

**Issue by jugutier** [JohnEstropia/CoreStore#200]
The example project we get when doing `pod lib try CoreStore` does not compile, because it is missing CoreStore framework.

**Comment by JohnEstropia** [comment]
Hi, I found the cause of this is that `pod try` opens the CoreStoreDemo project instead of the workspace file (even if cocoapods already downloaded the rest of the git directory).

I'm trying out a `yml` file that should open the workspace instead of the project. (develop branch)

**Comment by JohnEstropia** [comment]
`pod try CoreStore` now loads the xcworkspace. Let me know if it works for you.
For reference: https://github.com/JohnEstropia/CoreStore/pull/201

**Comment by jugutier** [comment]
Sounds great John. Thanks a lot, I’ll try it tomorrow.

**Comment by JohnEstropia** [comment]
Oops, I referenced the wrong link. The commit was here: https://github.com/JohnEstropia/CoreStore/commit/dc73cd6dd91602024c8655c33d7b99a5c624b534
