### ISSUE TITLE
Xcode 9 with cocoapods 

### ISSUE THREAD

**Issue by g535879** [JohnEstropia/CoreStore#202]
BaseDataTransation+importing.swift 
error:First type 'T.QueryableNativeType' in conformance requirement does not refer to a generic parameter or associated type

**Comment by eliseo-juan** [comment]
@g535879 Same bug, how did you solve it? Thanks

**Comment by g535879** [comment]
you can see  #184

use this:
pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'prototype/Swift_4_0'
and Pods -> CoreStore-> Bulid Settings -> Swift Language Version  Select Swift 4.0
