### ISSUE TITLE
Impossible to compile CoreStore 4.0 in xcode 9

### ISSUE THREAD

**Issue by igorkurylenko** [JohnEstropia/CoreStore#206]

**Comment by JohnEstropia** [comment]
Hi, I'm still finalizing the documentations for the `prototype/Swift_3_2` and `prototype/Swift_4_0` branches before releasing them, so in the meantime please use those branches for Xcode 9.

**Comment by jamesbebbington** [comment]
Is the compilation failure in `v4.1.3` a bunch of these type errors?

    First type 'O.QueryableNativeType' in conformance requirement does not refer to a generic parameter or associated type

Using 0aa8c03424d1304e250ac41fce3003252a12a74a on `prototype/Swift_3_2` I'm getting one compilation failure `Generic parameter 'U' could not be inferred` on the `addObserver` call in my `UITableViewCell` property:

```swift
var reply: Reply? {
    didSet {
        guard let reply = reply else { return }

        if let attachment = reply.attachment {
            self.attachmentMonitor = CoreStore.monitorObject(attachment)
            self.attachmentMonitor!.addObserver(self)
        } else {
            self.attachmentMonitor = nil
        }

        updateSubviews(with: reply)
   }
}
```

@JohnEstropia is there a specific branch/commit I should be using to build our app in Swift 3.2 in Xcode 9?

**Comment by MarijaS1** [comment]
@JohnEstropia when this issue will be resolved? I'm developing an app and my entire Core Data logic depends on your library :)

**Comment by jamesbebbington** [comment]
Scratch that issue above that I was having with `Generic parameter 'U' could not be inferred`; the bug was in my code.

**Comment by JohnEstropia** [comment]
@MarijaS1 Hi, if you are still having issues please check the solution here: https://github.com/JohnEstropia/CoreStore/issues/199

These compiler errors means that the CoreStore branch you are using doesn't match the Swift version of your app, specifically the Cocoapods swift version setting.

I'm closing this issue, but feel free to send a message if the problem persists.
