### ISSUE TITLE
Undoing changes

### ISSUE THREAD

**Issue by yoiang** [JohnEstropia/CoreStore#21]
Hey @JohnEstropia ! 
I've just started using CoreStore and I'm excited!

I was wondering, are there were any plans to expose some sort of undo functionality similar to or using the NSUndoManager? Or can something similar be achieved already with Unsafe Transactions?

Thanks!

**Comment by JohnEstropia** [comment]
@yoiang Thanks for the feedback!
If I remember correctly, the `undoManager` for all transactions should be intact, but direct access to the `NSManagedObjectContext` is currently not allowed on async and sync transactions. You are right that you can invoke undo operations on the `UnsafeDataTransaction` though!

```swift
let transaction = CoreStore.beginUnsafe()
// .. do some things
transaction.internalContext.undo()
```

Can you share your use-case for needing undo operations? If I find enough demand for it I might enable it on all transaction classes as well.

**Comment by yoiang** [comment]
Hey @JohnEstropia ! Sorry for the late response.

A use case I run into a fair bit is a View that visualizes a Model of some kind and let's say we provide a View and an Edit mode, during the life of the View the user may edit changes to the Model, press Cancel and undo all changes or undo particular changes, or press Done and have the changes committed.

Lemme know if I could be more specific or provide any more info.

**Comment by JohnEstropia** [comment]
@yoiang 
Okay, I think `UnsafeDataTransaction`s fits well for such cases. You should be able to implement this right now, but I'll add some utility methods to the transactions so we can save some typing :)

**Comment by JohnEstropia** [comment]
@yoiang 
Sorry, I just realized that the default `NSUndoManager` in iOS is `nil`, so you may need to create one and assign it to `transaction.internalContext.undoManager`. Another method is to recreate a new transaction with `beginUnsafe()` every time the user tries to undo all changes.

**Comment by yoiang** [comment]
@JohnEstropia 
Sounds good! If I notice a pattern with doing undo work with CoreStore that fits the CoreStore styling would you mind if I suggested a PR?

**Comment by JohnEstropia** [comment]
@yoiang 
>Sounds good! If I notice a pattern with doing undo work with CoreStore that fits the CoreStore styling would you mind if I suggested a PR?

I'd appreciate that! :)
