### ISSUE TITLE
ERROR: First type 'O.QueryableNativeType' in conformance requirement does not refer to a generic parameter or associated type

### ISSUE THREAD

**Issue by asadali737** [JohnEstropia/CoreStore#211]
I am facing an issue during compile time. Project is not building due to the issues I am facing. I recently updated my Xcode version to 9.0 and stuck at these issues

`/Pods/CoreStore/Sources/Value.swift:299:36: First type 'O.QueryableNativeType' in conformance requirement does not refer to a generic parameter or associated type
`

`/Pods/CoreStore/Sources/Value.swift:299:36: First type 'O.QueryableNativeType' in conformance requirement does not refer to a generic parameter or associated type
`

`/Pods/CoreStore/Sources/Value.swift:299:36: First type 'O.QueryableNativeType' in conformance requirement does not refer to a generic parameter or associated type
`

`/Pods/CoreStore/Sources/Value.swift:76:36: First type 'O.QueryableNativeType' in conformance requirement does not refer to a generic parameter or associated type
`

CoreStore (4.1.4)
Xcode 9.0
Pod version: 1.3.1

**Comment by JohnEstropia** [comment]
These compiler errors means that the CoreStore branch you are using doesn't match the Swift version of your app, specifically the Cocoapods swift version setting.

Please try the version 4.2.0 update which supports Swift 3.2.

If your app is running Swift 4.0, you need to indicate in your `Podfile` that CoreStore needs to be compiled as Swift 3.2:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'CoreStore'
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```

CoreStore's Swift 4.0 update is in the `prototype/Swift_4_0` branch, if you wish to use that instead. It will be pushed as version 5.0.0 in the following days.

I'm closing this issue, but feel free to send a message if the problem persists.
