### ISSUE TITLE
logical operations on where clause failed after upgrade to tree 5.0.0 (swift4 prototype)

### ISSUE THREAD

**Issue by paterik** [JohnEstropia/CoreStore#213]
Hi John

I've some issues after this mornings pod update process (migration from 4.1.3 to 5.0.0 of swift4 prototype).

- logical operators in where clause wont work anymore (ambiguous reference to member '&&', https://github.com/paterik/udacity-ios-aqoo/blob/master/aqoo/PlaylistViewControllerExt.swift#L22)
- transaction based fetching wont work on my current codebase (ambiguous reference to member 'fetchOne', https://github.com/paterik/udacity-ios-aqoo/blob/master/aqoo/PlaylistViewControllerExt.swift#L194)

Can you provide corresponding additions in your documentation to overcome those issues? Is there a (kind of) stable branch for swift4 code base available or planned within the next days/weeks? 

thanks and best regards,

Patrick

**Comment by JohnEstropia** [comment]
Hi, the 5.0.0 have huge breaking changes that would require some tweaks in your code. I’m still in the process of completing the migration instructions so in the meantime please use any 4.2.x commit directly.

To give you an idea what is happening, some FetchClauses including Where are now generic types. You now need to write it as `Where<YourEntity>(...)`. This is verbose, but there is also a new syntax that is a lot lot more typesafe and autocompletion-friendly. See https://twitter.com/johnestropia/status/883849193181204480
