### ISSUE TITLE
How to delete everything that was not part of the result of `importUniqueObjects`?

### ISSUE THREAD

**Issue by kevinrenskers** [JohnEstropia/CoreStore#217]
When I am importing objects from my remote server, I have something like this:

```
// Import objects
let objects = try transaction.importUniqueObjects(Into<T>(), sourceArray: source)

// Delete objects not part of the new collection
transaction.deleteAll(From<T>(), Where("NOT(self in %@)", objects))
```

So first I import the unique objects, then delete everything that wasn't part of this new collection. This used to work great! However now that I refactored to use CoreStoreObject, it's always removing _all_ objects. Apparently this Where clause does not work properly when used with CoreStoreObject.

Is there a way to get the same functionality working with CoreStoreObject?

**Comment by kevinrenskers** [comment]
Would I have to fetch all primary keys? I don't use a consistent property name for that though (giftId, userId, etc) so that makes it a little bit harder to work with.

**Comment by kevinrenskers** [comment]
Solved my own problem:

```
// Import objects
let objects = try transaction.importUniqueObjects(Into<T>(), sourceArray: source)

if !objects.isEmpty {
  // Delete objects not part of the new collection
  let ids = objects.map { $0.uniqueIDValue }
  transaction.deleteAll(From<T>(), Where("NOT(%K in %@)", type.uniqueIDKeyPath, ids))
}
```

**Comment by JohnEstropia** [comment]
@kevinrenskers You may also want to use the `!` operator on `Where`: 
```swift
transaction.deleteAll(From<T>(), !Where("SELF in %@", ids))
```

I recommend that you go through the README first. It's long but you'll find a lot of convenient way for common tasks.
