### ISSUE TITLE
SectionIndexTitles not working after refetch

### ISSUE THREAD

**Issue by zalogatomek** [JohnEstropia/CoreStore#218]
So, let me use your CoreStoreDemo app.

I've added this simple function: 

```swift
    override func sectionIndexTitles(for tableView: UITableView) -> [String]? {
        return ColorsDemo.palettes.sectionIndexTitles()
    }
```
to `ListObserverDemoViewController`.

At start, `sectionIndexTitles`works as expected (I can see them). But when I tap on `filterBarButtonItem` `sectionIndexTitles` dissapears.

I've tested it on version 4.2.1.

**Comment by JohnEstropia** [comment]
Thanks for the report!

I think this is because indexes are cached during FRC's fetch, which on ListMonitor.refetch() happens before the SectionBy is applied. I'll need to think how to handle this because the SectionBy closure may need to run on a background thread.
