### ISSUE TITLE
List monitor calling didDelete object instead of didUpdateObject

### ISSUE THREAD

**Issue by tomasgibas** [JohnEstropia/CoreStore#22]
I am using ListMonitor to fill in table view .When I update object on web and sync with app observer call did update object correctly. When I update one object within the application, observer call monitor did delete object. After relaunch of app the updated object again appears in table with updates. I am using same method to update object: transaction.importUniqueObject(Into, source).

**Comment by JohnEstropia** [comment]
@tomasgibas There is a current bug in `NSFetchedResultsController` ([which Apple seems to have no plans of fixing on iOS 8](https://openradar.appspot.com/22684413)), although it's the first time I've heard it send out delete events. 

What iOS version are you seeing this? Can you try how it behaves in iOS 9?

Some related posts:
http://stackoverflow.com/questions/31383760/ios-9-attempt-to-delete-and-reload-the-same-index-path/31384014#31384014
https://forums.developer.apple.com/message/9998#9998
https://forums.developer.apple.com/message/31849#31849

CoreStore tries to work around most of the bug's behavior, but it's not perfect so it would help if you can outline how to reproduce other conditions.

**Comment by tomasgibas** [comment]
Sorry for issue, I have found issue in my code. I was using empty Where statement, so on object update, fetch results controller thought  it does not match predicate any more.

—
S pozdravom / Best regards
Tomas Gibas
iOS Developer
GoodRequest, s.r.o.
web <http://www.goodrequest.com/> I twitter <https://twitter.com/gibastek> I facebook <https://www.facebook.com/gibastek>

**Comment by JohnEstropia** [comment]
@tomasgibas Okay, glad you fixed it! Feel free to report any other issues!
