### ISSUE TITLE
Crash on iOS9 after refetch on sectioned listMonitor

### ISSUE THREAD

**Issue by zalogatomek** [JohnEstropia/CoreStore#221]
So, I've added simple sectioned monitor to `StackSetupDemoViewController` like this:

```swift
class StackSetupDemoViewController: UITableViewController, ListObserver {
    
    let monitor = Static.facebookStack.monitorSectionedList(From<UserAccount>(), SectionBy("accountType"), OrderBy(.ascending("name")))

    @IBAction func refetch() {
        monitor.refetch(OrderBy(.ascending("name")))
    }

    typealias ListEntityType = UserAccount

    func listMonitorDidChange(_ monitor: ListMonitor<UserAccount>) {
        print("did change")
    }

    func listMonitorDidRefetch(_ monitor: ListMonitor<UserAccount>) {
        print("did refetch")
    }
```

I also added a `UIBarButtonItem` in Storyboard which performs `refetch` action.

Lastly, in `viewWillAppear`:

```swift
monitor.addObserver(self)
```

Now, every refetch fails with `EXC_BAD_ACCESS`:

![refetch_fail](https://user-images.githubusercontent.com/19666393/32551733-c6dd21dc-c491-11e7-996f-38d24e7544f5.png)

I didn't try it on iOS10, but on iOS11 works ok.

**Comment by JohnEstropia** [comment]
@zalogatomek Does this still happen if you add a `monitor.removeObserver(self)`  from the observer's `deinit`?

**Comment by zalogatomek** [comment]
@JohnEstropia Yes, it does.

**Comment by JohnEstropia** [comment]
@zalogatomek Thanks, I'll investigate. Can you tell which CoreStore branch or version you are using?

**Comment by zalogatomek** [comment]
@JohnEstropia I'm on `master`,  `4.2.2`. I have also checked `prototype/Swift_4_0` in some other project.

In my observation: this does not happen when using `CoreStoreObject`. In particular List Observer Demo uses `CoreStoreObject` with sectioned `ListMonitor`, but it works fine on iOS9.

But I can't (at least at the moment) check `CoreStoreObject` in mentioned project.

**Comment by JohnEstropia** [comment]
@zalogatomek Fixed this in the latest `4.2.3` version (master). Let me know if it works for you

**Comment by JohnEstropia** [comment]
For reference, this issue also had been haunting the `prototype/Swift_4_0` branch. The commit above was also merged there and I have confirmed that the Swift 4 branch is also fixed now.

**Comment by zalogatomek** [comment]
@JohnEstropia Works great, thanks
