### ISSUE TITLE
CoreStore not working on xcode9.1 

### ISSUE THREAD

**Issue by iOSUser110** [JohnEstropia/CoreStore#223]
It is giving errors

**Comment by JohnEstropia** [comment]
Can you give more details of the errors?

You might want to check if you are having the same issue as https://github.com/JohnEstropia/CoreStore/issues/222

**Comment by JohnEstropia** [comment]
Hi, I'm closing this issue as the current branches are confirmed to work correctly. Please check other the other issue threads and you may find something related to your problem.
