### ISSUE TITLE
Concurrent Cetching From CoreStore Async

### ISSUE THREAD

**Issue by SlinToWin** [JohnEstropia/CoreStore#224]
Use Case:
One Site in my App has two Data Models, one with many entries, one with a few.
When issuing a fetch on both of them on start, the heavy fetch blocks the small fetch because all transactions on CoreStore is done in a serial background queue.

Is there a way to concurrent fetch Data from Core Store asynchronous?

**Comment by JohnEstropia** [comment]
Just to clarify, your two fetches are both from inside transactions, correct?

If your two data models are unrelated to each other, I recommend separating their DataStack (and files). This way each model will have their own serial transactions.

The safety of CoreStore's transactions lie on the serial execution. If you wish to bypass this safety you can use a unsafe transactions (`dataStack.beginUnsafe()`) you can use freely on any queue. At that point, you are on your own with thread management.

**Comment by SlinToWin** [comment]
Yeah this is correct.
My thought was only some sort of concurrent read access, but sure there must be some sync managment. I have worked around that issue so i close this one. Thanks for your help.
