### ISSUE TITLE
NSBatchRequest @CoreStore?

### ISSUE THREAD

**Issue by shift00** [JohnEstropia/CoreStore#227]
Hi,
can anyone tell me, does CoreStore supports batch requests? I need write multiple changes into database on existing data, but I can't find good solution for this problem. 

For example NSBatchUpdateRequest seems like this: 
`let batchRequest = NSBatchUpdateRequest(entityName: "SomeEntity")
batchRequest.propertiesToUpdate = ["status": PointType.new.rawValue]
batchRequest.resultType = .updatedObjectIDsResultType`

**Comment by JohnEstropia** [comment]
Hi, batch requests are currently not yet implemented, sorry.
You should still be able to do this manually within transactions:
```swift
CoreStore.perform(
    asynchronous: { (transaction) in

        let batchRequest = NSBatchUpdateRequest(
            entity: CoreStore.defaultStack.entityDescription(for: YourEntity.self)!
        )
        batchRequest.propertiesToUpdate = ["status": PointType.new.rawValue]
        batchRequest.resultType = .updatedObjectIDsResultType
        transaction.unsafeContext().execute(batchRequest)
    },
    completion: { _ in /* ... */ }
)
```

**Comment by shift00** [comment]
It's working! Thanks.
