### ISSUE TITLE
AddStorage not working?

### ISSUE THREAD

**Issue by shift00** [JohnEstropia/CoreStore#228]
I have small issue with my project and CoreStore. I need to have sqlite db on start of my app. 
At **didFinishLauchingWithOptions** AppDelegate function I have this code:
`let dataStack: DataStack = DataStack(
            CoreStoreSchema(
                modelVersion: "V1",
                entities: [
                    Entity<Entity1CSModel>("Entity1"),
                    Entity<Entity2CSModel>("Entity2"),
                    Entity<Entity3Model>("Entity3")
                ]
            )
        )`

`  CoreStore.defaultStack = dataStack`

`CoreStore.addStorage(
            SQLiteStore(fileName: "MyDatabase.sqlite"),
            completion: { (result) -> Void in
                print("test")
        } )`

I noticed that completion handler is not called what throws the application when I want to create a new **Entity1** entity.

**Comment by shift00** [comment]
When I want to create/edit my entity I receive this error:
```
[CoreStore: Fatal Error] BaseDataTransaction.swift:83 create
  ↪︎ Attempted to create an entity of type 'Entity1CSModel', but a destination persistent store containing the entity type could not be found.
```

**Comment by JohnEstropia** [comment]
`addStorage()` is an asynchronous operation. Are you sure that your `create()` call is not being called before the `addStorage()` completes?

**Comment by shift00** [comment]
@JohnEstropia I moved block of code when is executed after `addStorage()` into completion handler and it's working ;) Thanks for tip 👍

**Comment by JohnEstropia** [comment]
That's great to hear :)
