### ISSUE TITLE
RxSwift support?

### ISSUE THREAD

**Issue by robertofrontado** [JohnEstropia/CoreStore#230]
Hey! Nice library you got here,

Are you planning to integrate RxSwift? that would be very nice 👍

**Comment by JohnEstropia** [comment]
You might want to check out RxCoreStore ([develop](https://github.com/JohnEstropia/RxCoreStore/tree/develop)).

This is a very rough alpha but we do use it in production apps.

**Comment by robertofrontado** [comment]
Thank you @JohnEstropia ! I'll have a look 👍
