### ISSUE TITLE
Update Relationship

### ISSUE THREAD

**Issue by KrishnaKaira** [JohnEstropia/CoreStore#238]
Getting error: 
❗ [CoreStore: Assertion Failure] DataStack+Querying.swift:105 fetchOne
  ↪︎ Attempted to fetch from a 'CoreStore.DataStack' outside the main thread.

I have 2 tables with one-many relation, I am using **importUniqueObjects** method to import data in the second table. from inside of `didInsert(from source: ImportSource, in transaction: BaseDataTransaction) throws` function I am not able to update the relationship.

Kindly help.

What is the right way to update relationship from inside importUniqueObjects method? A code snippet would help.

Below is my code snippet:

**insertion code:** 

` CoreStore.perform(
            asynchronous: { (transaction) -> Void in
                            _ = try! transaction.importUniqueObjects(Into<Content>(), sourceArray: data)
        },
            completion: { (result) -> Void in
                switch result {
                case .success: print("DATA SAVED SUCCESSFULLY!")
                case .failure(let error): print(error)
                }
        }`

**updating relationship:** (inside of `didInsert(from source:, in transaction: )` method)

`if let siteID = self.siteId {
            let filteredPred = "(siteId MATCHES '\(siteID)')"
           
            CoreStore.perform (
                asynchronous: { (transaction) -> Void in
                    
                    DispatchQueue.main.async {
                        
                        if var siteManagedObject = CoreStore.fetchOne(From<Site>(), Where<Site>(NSPredicate(format: filteredPred))) {
                            
                            siteManagedObject = transaction.edit(siteManagedObject)!
//                            let contentObj = transaction.edit(self)!
                            
                            siteManagedObject.addToSiteContent(self)
//                            contentObj.contentSite = siteManagedObject
                            self.contentSite = siteManagedObject
                        }
                    }
            },
                completion: { _ in } )`

**Comment by JohnEstropia** [comment]
Don't dispatch asynchronously from inside `didInsert(from:in:)`. Use the `transaction` argument directly:
```swift
func didInsert(from source: ImportSource, in transaction: BaseDataTransaction) throws {
    guard if let siteID = self.siteId else {
        return
    }
    guard if let siteManagedObject = transaction.fetchOne(From<Site>(), Where<Site>("siteId", isEqualTo: siteID)) else {
        return
    }
    siteManagedObject.addToSiteContent(self)
    // Your relationships should have their inverse-relationships set, in which case you don't need to call
    // self.contentSite = siteManagedObject
}
```

**Comment by KrishnaKaira** [comment]
Hi JohnEStropia,

Thanks for the quick reply, I wish I had asked here before wasting my whole day to find a workaround. Thanks a lot for your reply it worked pretty well.

**Comment by JohnEstropia** [comment]
Just a hunch, but `MATCHES` issues a regular expression query. Try using  `Where<T>.init(_:isEqualTo:)` , or a variant of it, instead.

**Comment by JohnEstropia** [comment]
Closing this issue due for now. Let me know if the issues persist.
