### ISSUE TITLE
Crash while trying refetch listMonitor after data stack is recreated.

### ISSUE THREAD

**Issue by sidlatau** [JohnEstropia/CoreStore#241]
Hi, I am recreating database by physically deleting/moving DB files after each login to app. 
After file is moved I recreate data stack by calling: 
```
let dataStack = DataStack(
            xcodeModelName: "..."
        )
try dataStack.addStorageAndWait(
                SQLiteStore(
                    fileURL: sqliteFileURL,
                    localStorageOptions: .allowSynchronousLightweightMigration
                )
            )
```
But if ListMonitor was created on old data stack I get crash there:
```
internal func applyToFetchRequest<ResultType>(...) {
fetchRequest.entity = context.parentStack!.entityDescription(for: EntityIdentifier(self.entityClass))!
...
```
`parentStack` there is `nil`.

This refetch is called from this observer:
```
self.observerForDidChangePersistentStore = NotificationObserver(...)
...
if previousStores != currentStores {
                        
                        self.refetch(self.applyFetchClauses)
                    }
...
```
I am using CoreStore v5.0.0.

Maybe there is a better way to recreate data stack or only one storage in that stack? I see there is method `storage.cs_eraseStorageAndWait` but it is specifically indicated not to use it directly.

**Comment by JohnEstropia** [comment]
@sidlatau Have you solved your issue? I personally don't recommend moving SQLite files around, but if you really need to, just make sure that
1. you also move any `-wal` files
2. you recreate everything that was created from the old stack, including objects and `ListMonitor`s

**Comment by sidlatau** [comment]
No, I haven't solve the issue, I just stopped using `ListMonitor`s . Despite that issue I am happily using CoreStore :)   Thank you for your feedback.

**Comment by tosbaha** [comment]
I had similar problems. I was using AppDelegate to initialize data stack and had `ListMonitor` in my main view. The thing is, in storyboard environments, viewDidLoad is called before AppDelegate and this messes up things. I learned my hard lesson that you shouldn't depend on AppDelegate. My approach is something like below

```swift
struct Storage {
    static let stack: DataStack = {
        let stack = DataStack(xcodeModelName: "Kargo",migrationChain: ["Kargo","KargoV2"])
        let sqliteFileURL = URL(....)
        try! stack.addStorageAndWait(
            SQLiteStore(fileURL: sqliteFileURL,  localStorageOptions: .allowSynchronousLightweightMigration)
        )
        return stack
   //If you prefer CoreStore functions, add to defaultStack

    }()

    static let kargos:ListMonitor<KargoCD> =  {
        return Storage.stack.monitorList(
            From<KargoCD>(),
            Where<KargoCD>(filter.predicate),
            OrderBy<KargoCD>((sort.descriptor))
        )
    }()
}

// The use it like below in your ViewController viewDidLoad

        Storage.kargos.addObserver(self)


```

**Comment by JohnEstropia** [comment]
@tosbaha Thanks for the feedback. Your pattern is the best practice as it is explicit about the initialization timing. 

I am closing this issue as the OP seems to have gone to a different route to solve the issue.
