### ISSUE TITLE
Demo App is Not compiling

### ISSUE THREAD

**Issue by msalmanST** [JohnEstropia/CoreStore#248]
Hi,

I just download the code and trying to run the demo app, but I am getting below errors, let me know what I am doing wrong. I am using Xcode 9.2.

![screen shot 2018-04-26 at 12 23 03 pm](https://user-images.githubusercontent.com/1397019/39291610-0559b17e-494d-11e8-8ef6-5ae82f0e2cd0.png)

**Comment by JohnEstropia** [comment]
The latest version (`5.1.0`) is built for Swift 4.1 (Xcode 9.3).

If you wish to use Swift 4 and Xcode 9.2, please use the `5.0.0` version.

**Comment by wolffan** [comment]
Hey @msalmanST as the maintainer says the project has been updated to Swift 4.1 on the version `5.1.0` you just need to change the entry of the Podfile to the new version. If you're using `pod update` won't work if you fix the version to `5.0.0` remove the version number and you'll be able to update it naturally.
