### ISSUE TITLE
carthage issue

### ISSUE THREAD

**Issue by demonar** [JohnEstropia/CoreStore#25]
When adding the project as a carthage dependency i get the following error:

A shell task failed with exit code 128:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by PaulWoodIII** [comment]
Just a quick response but that seems like a Carthage / Git configuration error not a CoreStore error.

**Comment by demonar** [comment]
It is related to CoreStore as i have other libraries working without issues, i can try to get only CoreStore to see if the issue is related to having CoreStore and other libs at the same time.

**Comment by demonar** [comment]
$ carthage update --platform ios
*** Fetching CoreStore
*** Checking out CoreStore at "1.3.4"
A shell task failed with exit code 128:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by demonar** [comment]
This are the other libraries i have and they're building just fine:

*** Fetching PKHUD
*** Fetching ObjectMapper
*** Fetching AlamofireImage
*** Fetching Alamofire
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out PKHUD at "2.2.5"
*** Checking out ObjectMapper at "1.0.1"
*** Checking out AlamofireImage at "2.1.1"
*** Checking out Alamofire at "3.1.3"
*** Checking out Result at "1.0.0"
*** Downloading ReactiveCocoa.framework binary at "v4.0-alpha.4"
*** xcodebuild output can be found in /var/folders/5k/tpwkj4kj2jj0l9p1h85ntp_c0000gn/T/carthage-xcodebuild.oAk1EZ.log

**Comment by PaulWoodIII** [comment]
Whats your Cartfile look like?

**Comment by demonar** [comment]
github "ReactiveCocoa/ReactiveCocoa" >= 4.0
github "Alamofire/Alamofire" >= 3.0
github "Alamofire/AlamofireImage" >= 2.0
#github "gitdoapp/sugarrecord"
github "JohnEstropia/CoreStore" >= 1.3.0
github "Hearst-DD/ObjectMapper" >= 1.0
github "pkluz/PKHUD"

**Comment by demonar** [comment]
Could that be related to that you have GCDKit as a submodule?

**Comment by PaulWoodIII** [comment]
using just github "JohnEstropia/CoreStore" >= 1.3.0 in a clean project I can't reproduce the error when running `carthage bootstrap` 

The `Permission denied (publicly).` makes me think its a git problem

you've got a point about the GCDKit submodule, what version of Carthage are you using?

**Comment by demonar** [comment]
it's 0.10.0

**Comment by demonar** [comment]
i run "carthage update --platform ios" to get the latest and build only for ios to avoid creating extra lib files

**Comment by demonar** [comment]
This is the result of running bootstrap on my cartfile:

$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching PKHUD
*** Fetching ObjectMapper
*** Fetching CoreStore
*** Fetching AlamofireImage
*** Fetching Alamofire
*** Fetching ReactiveCocoa
*** Fetching Result
*** Downloading ReactiveCocoa.framework binary at "v4.0-alpha.4"
*** Checking out AlamofireImage at "2.1.1"
*** Checking out Result at "1.0.0"
*** Checking out ObjectMapper at "1.0.1"
*** Checking out Alamofire at "3.1.3"
*** Checking out PKHUD at "2.2.5"
*** Checking out CoreStore at "1.3.4"
A shell task failed with exit code 128:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by demonar** [comment]
As GCDKit is a submodule and it's not declared as a carthage dependancy, carthage is not able to resolve it, also, as you are the developer you might have no issues on getting the submodule, i think that's why i get the error, i'll try to add GCDKit as another carthage dependency to check if that solves the issue

**Comment by demonar** [comment]
Tried with no luck

**Comment by PaulWoodIII** [comment]
I'm not the developer, I've got no special access to the repo

**Comment by demonar** [comment]
no worries, @JohnEstropia , i got it working by making these changes:

https://github.com/demonar/CoreStore

the tag 1.3.5 has GCDKit as a Carthage dependency and the resulting call to carthage update was:

$ carthage update --platform ios
*** Fetching PKHUD
*** Fetching ObjectMapper
*** Fetching CoreStore
*** Fetching AlamofireImage
*** Fetching Alamofire
*** Fetching ReactiveCocoa
*** Fetching GCDKit
*** Fetching Result
*** Checking out AlamofireImage at "2.1.1"
*** Checking out ObjectMapper at "1.0.1"
*** Checking out PKHUD at "2.2.5"
*** Checking out Result at "1.0.0"
*** Checking out GCDKit at "1.1.4"
*** Downloading ReactiveCocoa.framework binary at "v4.0-alpha.4"
*** Checking out CoreStore at "1.3.5"
*** Checking out Alamofire at "3.1.3"
*** xcodebuild output can be found in /var/folders/5k/tpwkj4kj2jj0l9p1h85ntp_c0000gn/T/carthage-xcodebuild.RJkj4Z.log

**Comment by demonar** [comment]
If you want i can fill a pull request so you can include these changes on the repo.

**Comment by JohnEstropia** [comment]
@demonar Can you check if the 1.3.4 tag works for you? I just discovered this as well yesterday when I was setting up Travis-CI builds.
Relevant commit: https://github.com/JohnEstropia/CoreStore/commit/03da3544f67fecf1361753eec714d2003d4fa1f7

**Comment by JohnEstropia** [comment]
@demonar Can I check your pull request?
I find it weird you got it working because CoreStore never had a 1.3.5 tag...

**Comment by demonar** [comment]
Sorry for the late answer, yes, i added the 1.3.5 tag on my fork to make it work, otherwise Carthage won't take the commit.

**Comment by demonar** [comment]
By the way, AWESOME DB library, thumbs up

**Comment by JohnEstropia** [comment]
@demonar 
>i removed GCDKit as a submodule and added it as a carthage dependency

I see what you mean now. Unfortunately, I can't remove GCDKit's submodule as that will break the build for non-Carthage users. Hopefully my commit made it work for everyone.

>By the way, AWESOME DB library, thumbs up

Thanks! Feel free to report any other issues you find :)
