### ISSUE TITLE
Framework not found

### ISSUE THREAD

**Issue by nazywamsiepawel** [JohnEstropia/CoreStore#261]
Hey all,

I'm trying to add CoreStack to a project. So far it seems to be much more troublesome than it should. The problem seems to occur both when trying to install CoreStack into an existing project as well as into a completely fresh one. 

1. I start a new empty xcode project
2. From terminal, I run pod init & pod install to create the workspace. I build the project successfully. 
3.  I open Podfile, add `pod 'CoreStore', '~> 5.0'` under `use_frameworks!`
4. I run `pod install` again and then `pod update`
5. I open the workspace and the project doesn't compile anymore. 

`
ld: warning: directory not found for option '-F/Users/pawel/Library/Developer/Xcode/DerivedData/SignOnGlass-euboxdzjihwiqedafbmptgbjdbqf/Build/Products/Debug-iphonesimulator/CoreStore'
ld: framework not found CoreStore
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

This seems to happen every time and only when I install CoreStore. Is there some magical trick required to get CoreStore to work with Cocoapods? Am I doing something wrong?

My environment:
- xcode Version 9.4 (9F1027a)
- cocoapods-1.5.3
- swift 4

**Comment by JohnEstropia** [comment]
@nazywamsiepawel Does this happen with the `5.1.1` version as well?
Also, do you restart Xcode after the `pod update`?
