### ISSUE TITLE
[CoreStore: Fatal Error] BaseDataTransaction.swift:83 create

### ISSUE THREAD

**Issue by shift00** [JohnEstropia/CoreStore#262]
Hello, I have very annoying problem with CoreStore. I start the application and sometimes I get an error which can be seen below. What can I do with this?

❗ [CoreStore: Fatal Error] BaseDataTransaction.swift:83 create
  ↪︎ Attempted to create an entity of type 'SampleCSModel', but a destination persistent store containing the entity type could not be found.

**Comment by shift00** [comment]
Hint: My code with `addStorage...` is executed in AppDelegate in `didFinishLaunchingWithOptions`

**Comment by JohnEstropia** [comment]
It is highly likely you are accessing your entities before the `addStorage()` method's `completion` is called. Please make sure your view controllers are not accessing your data before that.

You can easily check this by adding a breakpoint inside the `completion` closure and inside the `CoreStore.defaultStack` getter, then make sure that the `defaultStack` is called only from the `CoreStore.addStorage()` call.
