### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by VincentSit** [JohnEstropia/CoreStore#267]
I am trying to use CoreStore in my project, I found that all fields in the Demo are declared with `let` , and there seems to be no way to set access controls, i.e. read-only variables.

A very common usage scenario is:

```
final class User: CoreStoreObject {

  // Cannot be modified after initialization.
  let identifier = Value.Requited<String>("identifier", initial: "")

  // Can only be modified internally.
  private(set) var name = Value.Optional<String>("name")

  func update(name: String?, completion: Completion?) {
    // Perform a network request...
    self.name = name
  }
}

```

In the above example, I want to only allow `name` to be modified inside the class, the external can only be read.

What should I do?

**Comment by JohnEstropia** [comment]
Make the property `private` and expose it through a computed property:
```swift
final class User: CoreStoreObject {
  var name: String? {
       return _name.value
  }
  private let _name = Value.Optional<String>("name")
}
```

**Comment by VincentSit** [comment]
Thank you.
