### ISSUE TITLE
Unable to submit to app store with library

### ISSUE THREAD

**Issue by demonar** [JohnEstropia/CoreStore#27]
When trying to upload a binary to the app store that contains the library, i'm getting the error ITMS-90206, this is due to the library containing the standard swift files in it, they should be excluded to avoid the issue, if you look at the screenshots i compared this with alamofire and they exclude the libraries.

![screen shot 2015-12-08 at 04 10 30](https://cloud.githubusercontent.com/assets/1742284/11649806/ac356f82-9d61-11e5-8aed-19c05a1c13f3.png)
![screen shot 2015-12-08 at 04 09 56](https://cloud.githubusercontent.com/assets/1742284/11649805/ac352c20-9d61-11e5-9738-9cc680ec6a4b.png)

**Comment by demonar** [comment]
To solve it you'll need to follow this solution: http://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr

![screen shot 2015-12-08 at 04 17 18](https://cloud.githubusercontent.com/assets/1742284/11649900/ba10ebd0-9d62-11e5-8ad7-3b11133ad26a.png)

**Comment by JohnEstropia** [comment]
@demonar Thanks for catching that! I pushed a 1.3.6 tag, hope it works for you now.
We always use Cocoapods for our own projects so apologies if the previous .xcproj settings wasn't stable.

**Comment by demonar** [comment]
no worries, you'll have to add this too:

http://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr
![screen shot 2015-12-08 at 04 43 52](https://cloud.githubusercontent.com/assets/1742284/11650271/5a940a30-9d66-11e5-8d5b-df73d8bffded.png)

**Comment by demonar** [comment]
if you can, revert those changes, after that i started getting an error with the GCDKit, i'll investigate the issue and give you an answer later

**Comment by demonar** [comment]
Got 1.3.6 and added GCDKit as another carthage dependency and made the trick, there can't be nested libraries, i think that the only way to make it work is to add it as a carthage dependency instead of being a module

**Comment by JohnEstropia** [comment]
Thanks for the investigation!

I'm not sure how to reconcile Carthage's behavior without breaking builds for submodule users...
According to the discussion [here](https://github.com/Carthage/Carthage/issues/844) and [here](https://github.com/Carthage/Carthage/issues/917), dependencies should be linked in the app level, which the way I understand it is to include all of them in the the main app's Cartfile.

I did try adding a Cartfile to CoreStore that includes GCDKit, but it seems that Carthage ignores it either way. You'll still have to add GCDKit to your app's Cartfile (I'll update the README to indicate this)

So it seems we have two choices,

1. Fully support Carthage by removing the submodule. (breaks build submodule users)
2. Keep the current setup but advise non-Cocoapods users to incude the script
```
cd "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/"
if [[ -d "Frameworks" ]]; then 
    rm -fr Frameworks
fi
```
as a build phase to their app.

I also prefer method 1, so I'll see if there is any way we can make it work without removing the submodule. If you already have a working branch ill be glad to try it out, just send a pull request.

**Comment by demonar** [comment]
On the branch that i created GCD was a carthage dependency and it was working, the problem is that you need to support both, carthage and pods, it seems that currently some developers are having the same issue i had when they have libraries that include libraries, you could try and take a look at ReactiveCocoa, they have a couple of libraries included and there's no issue on submitting that to the app store.
They also include instructions for different kind of users.

**Comment by JohnEstropia** [comment]
@demonar I think I can see how to do this with CoreStore. ReactiveCocoa also avoids nested libraries by linking everything through a workspace. To do the same I might need to update CoreStore's major version as I'm pretty sure it will break builds for current non-Cocoapods, non-Carthage users.

Thanks for looking into this, I really appreciate it! I hope you have your fork working for you for now because I don't know when I'll be able to push a working fix, but I'll try to get it done by next week.

**Comment by demonar** [comment]
No worries, i'm glad to have helped on something, i think i'll be able to help giving some examples on how to integrate CoreStore and Alamofire in the future, i'm currently working on that in a project and got a really neat API class.
For now, the carthage build i have is working and i don't plan on updating it in the near future. i've been submitting test builds to itunes connect without any issues.

**Comment by JohnEstropia** [comment]
@demonar Just to give you a heads up, I updated the project structure to use a workspace instead instead of nested projects. You can check out the 1.4.0 tag. Tell me if you have any problems!

**Comment by demonar** [comment]
Awesome, I'll give it a try, thanks for the heads up!
