### ISSUE TITLE
CoreStore Pod not working on Objective C only Project

### ISSUE THREAD

**Issue by HabibAliAtFolio3** [JohnEstropia/CoreStore#270]
Please help Core Store pod not working in Objective C only Project
[Test.zip](https://github.com/JohnEstropia/CoreStore/files/2359967/Test.zip)

**Comment by JohnEstropia** [comment]
There's no way around it, you have to install Pods with `use_frameworks!`. CoreStore supports Objective-C, but it's built primarily in Swift so you cannot import it through a static library.

**Comment by HabibAliAtFolio3** [comment]
Ok Thanks
