### ISSUE TITLE
Xcode 10 importUniqueObjects Into<T>() issue

### ISSUE THREAD

**Issue by ps-mmaierhuber** [JohnEstropia/CoreStore#271]
Hey there,

This works totally fine in any Xcode 9 but fails to compile in Xcode 10 (beta and GM), when trying to import:
`Cannot convert value of type 'Into<T>' to expected argument type 'Into<_>'`

```swift
class BaseModel: CoreStoreObject, ImportableUniqueObject {...}

func importObjects<T: BaseModel, S: Sequence>(into: T.Type, source: S, completion: @escaping ParseCompletion<T>) where S.Iterator.Element == T.ImportSource {
     CoreStore.perform(asynchronous: { (transaction) -> [T] in

    let imported = try transaction.importUniqueObjects(Into<T>(), sourceArray: source) // complaining here
    // ...
}
```

Any hints?

**Comment by JohnEstropia** [comment]
@ps-mmaierhuber I'm more surprised this compiles in Xcode 9 at all. `Into()` needs a generic type, in your case try `Into<T>()` instead of `Into()`.

**Comment by ps-mmaierhuber** [comment]
@JohnEstropia sorry that was a typo reducing the example, i am using Into<T>()
I also tried
Into<BaseModel>(T.self)

**Comment by JohnEstropia** [comment]
I'm guessing your `importObjects ` method isn't binding your generic types properly. Or that you have another compiler error somewhere that is masked by this error message. Can you show your whole `func importObjects(...)` implementation?

**Comment by ps-mmaierhuber** [comment]
Yeah the thing that i dont understand is that it works with any Xcode 9, but not with Xcode 10 ... 
There is the code and how it is called, including the first type inference.

```swift
    func importObjects<T: BaseModel, S: Sequence>(into: T.Type, source: S, completion: @escaping ParseCompletion<T>)
        where S.Iterator.Element == T.ImportSource {

            CoreStore.perform(asynchronous: { (transaction) -> [T] in
                let imported = try transaction.importUniqueObjects(Into<T>(), sourceArray: source)
                return imported
            }, success: { (objects) in
                let fetchedObjects = CoreStore.fetchExisting(objects)
                completion(fetchedObjects, nil)
            }, failure: { (_) in
                completion(nil, nil)
            })
    }
```

and its called from the response parser like this:

```swift
    func parseResponse<T: BaseModel>(_ response: Response, rootObject: String? = nil, then completion: @escaping ParseCompletion<T>) throws {
        let filteredResponse = try response.filterSuccessfulStatusCodes()
        var json = try JSON(data: filteredResponse.data).preProcessedJSON
        if let rootObject = rootObject {
            json = json.first?[rootObject].preProcessedJSON ?? json
        }
        DatabaseManager.shared.importObjects(into: T.self, source: json, completion: completion)
    }
```

```swift
    func handleImportableResult<T: BaseModel>(_ result: Result<Moya.Response, Moya.MoyaError>, rootObject: String? = nil, then parseCompletion: @escaping ParseCompletion<T>) {
        switch result {
        case .success(let response):
            do {
                try self.parseResponse(response, rootObject: rootObject, then: parseCompletion)
            } catch let error {
                ...
            }
        case .failure(let failure):
            ...
        }
    }
```

Im using Moya... but here the generic T is inferred to a concrete model, User is a subclass of BaseModel.
```swift
    func getUser(then completion: @escaping ParseCompletion<User>) {
        provider.request(.getUser) { (result) in
            self.handleImportableResult(result, then: completion)
        }
    }
```

The ParseCompletion is a typealiased generic:
```swift
   typealias ParseCompletion<T: BaseModel> = (_ objects: [T]?, _ error: APIError?) -> Void
```

**Comment by JohnEstropia** [comment]
@ps-mmaierhuber In your `func importObjects` implementation, can you try if this works?
```swift
transaction.importUniqueObjects(Into(into), sourceArray: source)
```

**Comment by ps-mmaierhuber** [comment]
Doesnt work. I tried:
`Into<T>(into)`
and
`Into(into)`

also tried specifying the returned objects type to T, also tried using BaseModel, doesnt work. It is always complaining about this argument in importUniqueObjects

These things works just fine if i add them there:
```swift
transaction.create(Into<T>())
let objects = transaction.fetchAll(From<T>())
```

**Comment by bendalton** [comment]
I too would like the answer 👍  Hi @ps-mmaierhuber !

**Comment by JohnEstropia** [comment]
@ps-mmaierhuber @bendalton Can any of you isolate the models and methods in a separate project? The app doesn't need to run, just a reproduction of the compiler error would greatly help.

**Comment by puelocesar** [comment]
@JohnEstropia Here: https://github.com/puelocesar/CoreStoreTest

Builds with Xcode 9 but not on Xcode 10

**Comment by JohnEstropia** [comment]
@puelocesar That was really helpful, thanks!

This looks bizarre. It actually works if we use `where T: ImportableUniqueObject, S.Iterator.Element == T.ImportSource` for the function constraint, albeit the obviously ignorable compiler warning.

I'm pretty sure we hit a compiler issue here. I'll try to raise this in the [Swift bug tracker](https://bugs.swift.org/secure/Dashboard.jspa) within the weekend. Let me know if any of you already have a ticket/rdar so I can duplicate.

**Comment by puelocesar** [comment]
I'm getting `Redundant conformance constraint 'T': 'ImportableUniqueObject'` as a Swift warning, but other then that, it works, thanks!

**Comment by JohnEstropia** [comment]
Reported in Swift bug tracker: https://bugs.swift.org/browse/SR-8945
