### ISSUE TITLE
Type 'CoreStoreObject' does not conform to protocol 'Hashable'

### ISSUE THREAD

**Issue by jayantnd** [JohnEstropia/CoreStore#274]
the recent pod version is not compiling. showing below errors:

Using CoreStore (5.3.1)

**Type 'CoreStoreObject' does not conform to protocol 'Hashable'
Use of undeclared type 'Hasher'**

**Comment by JohnEstropia** [comment]
@jayantnd Hi, If you are still on Swift 4.1 and below, you don't need to update to 5.3.1 yet. 
If you are already using Xcode 10, please make sure that CoreStore is being compiled as `Swift 4.2`
