### ISSUE TITLE
Crash: looking for .momd file when using CustomMappingProvider

### ISSUE THREAD

**Issue by mbain** [JohnEstropia/CoreStore#280]
I get the following crash when using a CustomMappingProvider:
```
❗ [CoreStore: Fatal Error] XcodeDataModelSchema.swift:57 from(modelName:bundle:migrationChain:)
  ↪︎ Could not find "Tocca.momd" from the bundle "io.tocca.ina". Other model files in bundle: 0 item(s) []
```
Both models are CoreStoreObjects, and I do not have a .xcmodeld file.  As such, I don't have a good way to generate a .momd file.  My understanding of the situation is that CoreStore should be able to handle the migration given the CustomMappingProvider, without a .momd file.  Am I missing something?

**Comment by JohnEstropia** [comment]
@mbain This usually means you are accessing `CoreStore` somewhere earlier than your `DataStack` creation, which would trigger creation of a lazy, default-configured `DataStack`. You can put a breakpoint inside `get` in `public static var defaultStack: DataStack` inside *CoreStore.swift* to see where in your code triggers the lazy creation.
