### ISSUE TITLE
Chain .where clause

### ISSUE THREAD

**Issue by markst** [JohnEstropia/CoreStore#283]
There doesn't seem to be any documentation on whether chaining multiple `where` clauses is possible?

It appears the following doesn't work:
```swift
return CoreStore.fetchCount(
    From<Booking>()
        .where(\.customer == self)
        .where(\.bookingStatus == BookingStatus.cancelled.rawValue)
    ) ?? 0
```

and must be expressed as a single predicate.

**Comment by markst** [comment]
https://github.com/JohnEstropia/CoreStore/blob/45e110755dd5ac3af201b9d8ff16f2af909f6539/Sources/Where.swift#L273

**Comment by JohnEstropia** [comment]
You can use `&&` and `||` operators instead:
```swift
return CoreStore.fetchCount(
    From<Booking>()
        .where(\.customer == self && \.bookingStatus == BookingStatus.cancelled.rawValue)
    ) ?? 0
```

**Comment by markst** [comment]
Thanks. Just no mention of it in readme.
