### ISSUE TITLE
Unsafe transaction changes not persisted to disk if save() called on context

### ISSUE THREAD

**Issue by markst** [JohnEstropia/CoreStore#285]
I'm using a `UnsafeDataTransaction` in combination with `ListMonitor` which I display results in progress prior to committing saved changes. 

My `ListMonitor` does not update with results unless I call:
```swift
try? transaction.unsafeContext().save()
```

However upon attempting to persist my changes such as:
```swift
transaction?.commit({ [weak self] (error) in
    if error == nil {
        self?.navigationController?.popViewController(animated: true)
    } else {
        ErrorHandler.showError(with: error?.localizedDescription ?? "Error Occured...")
    }
})
```

My changes are not correctly written to persisted store.

**Comment by markst** [comment]
If I force saving on the parent context:
```swift
try? transaction?.unsafeContext().parent?.save()
```
The changes are correctly persisted.

**Comment by JohnEstropia** [comment]
How do you confirm that the changes are not persisted?
Do you get an error within the `commit` block?

**Comment by markst** [comment]
No error. I perform a fetch later on in the app's lifetime & no results are returned.

It appears due to `self.hasChanges` guard returning early & never breaking into saving the parent:  
https://github.com/JohnEstropia/CoreStore/blob/40f458a09c0177d15ceab1561acaede2799c4f2d/Sources/NSManagedObjectContext%2BTransaction.swift#L186

**Comment by markst** [comment]
@JohnEstropia 
On further investigation it seems I should be using `flush()`. #71
This produces the desired effect with `commit()` correctly persisting to disk.

Is it all good to simply destroy the transaction if I changes should not be persisted?

**Comment by JohnEstropia** [comment]
@markst Yes, discarding the transaction will remove all unsaved changes.
