### ISSUE TITLE
Custom schema mapping with copyEntity fails with renaming ids

### ISSUE THREAD

**Issue by ianbytchek** [JohnEstropia/CoreStore#300]
I'm coming across a case with custom mapping provider that fails due to use of renaming identifiers in source attributes. A simplified scenario:
- Migration from v1 to v2 to v3.
- v1 has `oldFoo` attribute.
- v2 has `newFoo` attribute with `fooOld` renaming id for lightweight migration from v1.
- Migration from v2 to v3 fails because explicitly unwrapped source attribute doesn't exist…

I believe it narrows down to [CustomSchemaMappingProvider.swift#L425](https://github.com/JohnEstropia/CoreStore/blob/45e110755dd5ac3af201b9d8ff16f2af909f6539/Sources/CustomSchemaMappingProvider.swift#L425) line:

```swift
let sourceAttributes = sourceEntity.cs_resolvedAttributeRenamingIdentities()
let destinationAttributes = destinationEntity.cs_resolvedAttributeRenamingIdentities()
var attributeMappings: [NSPropertyMapping] = []
for (renamingIdentifier, destination) in destinationAttributes {
    
    // 👇 The part goes down!
    let sourceAttribute = sourceAttributes[renamingIdentifier]!.attribute
    let destinationAttribute = destination.attribute
    let propertyMapping = NSPropertyMapping()
    propertyMapping.name = destinationAttribute.name
    propertyMapping.valueExpression = NSExpression(format: "FUNCTION($\(NSMigrationSourceObjectKey), \"\(#selector(NSManagedObject.value(forKey:)))\", \"\(sourceAttribute.name)\")")
    attributeMappings.append(propertyMapping)
}
return attributeMappings
```

The call above to `cs_resolvedAttributeRenamingIdentities()` returns source attributes dictionary organized by renaming id when they are present, or by name otherwise, but really should return them organized by attribute name only. In other words, instead of resolving renaming source attributes for v2 as `["newFoo": …]` it returns them as `["oldFoo": …]`, but `"oldFoo"` isn't available in source entity v2.

**Comment by JohnEstropia** [comment]
I'll comment on #301 if there's anything that comes up. Thanks again!
