### ISSUE TITLE
shouldUpdateFromImportSource and shouldInsertFromImportSource functionalities are unclear

### ISSUE THREAD

**Issue by demonar** [JohnEstropia/CoreStore#31]
In the case of importUniqueObject... shouldUpdateFromImportSource is never checked and the update is always called, this makes the protocol usage unclear, if the intended usage would be to check if the elements should be created/updated/untouched, this is an error, please fix/clarify.

**Comment by JohnEstropia** [comment]
@demonar Definitely an error. Thanks!
