### ISSUE TITLE
Updating existing set of relationships issue

### ISSUE THREAD

**Issue by matrosovDev** [JohnEstropia/CoreStore#318]
Hi could someone help or explain where I did mistake

I try to update workout.muscles Swift.Set which is a relationship One Workout To Many Muscles.

For the first call all works good, but all next calls just add only new inserted object to fetchExisting others seems are stored in some background context.

Here is a link to question:

https://stackoverflow.com/questions/55921312/corestore-insert-array-as-relationship-objects-while-updating-data-model

**Comment by JohnEstropia** [comment]
Hi, this would be a the general behavior of `NSManagedObject`s with regards to to-many properties.

First, as you have found out, the inverse relationship is important.

Second, `Set` is not recommended for unordered `@NSManaged` properties. Please use `NSSet`.
In that note, it should be treated as immutable. Which means you cannot insert objects directly to the `NSSet` value. There are two ways you can insert values.

1. Assigning a new `NSSet` directly:
```swift
var muscles = (workout.muscles as! Set?) ?? []
muscles.insert(newMuscle)
workout.muscles = muscles as NSSet
```

2. Use KVO mutable accessors (creates an `NSMutableSet` proxy for you):
```swift
workout.mutableSetValueForKey(#keyPath(WorkoutEntity.muscles)) 
    .addObject(newMuscle)
```

**Comment by matrosovDev** [comment]
As John suggested we need to declare properties as NSSet instead Set and then we can use 2 code fragments above to make it done.

Answered here as well:
https://stackoverflow.com/questions/55921312/corestore-insert-array-as-relationship-objects-while-updating-data-model
