### ISSUE TITLE
sectionIndexTitles and sectionForSectionIndexTitle

### ISSUE THREAD

**Issue by markkrenek** [JohnEstropia/CoreStore#32]
How do we get access to NSFetchedResultsController's sectionIndexTitles and sectionForSectionIndexTitle when using a sectioned list?

**Comment by JohnEstropia** [comment]
@markkrenek There's currently no interface to expose these (yet). Let me push an update within the day.
If you need to, you can workaround with these:

Getting Section Index Titles:
```swift
let monitor = // ... ListMonitor
let sectionIndexTitles: [String] = (0 ..< monitor.numberOfSections())
    .map({ monitor.sectionInfoAtIndex($0) })
    .map({ $0.indexTitle ?? "" })
// Apple's documentation states:
// "The default implementation returns the array created by calling sectionIndexTitleForSectionName: on all the known sections."
// which is similar to what we're doing here
```
        
Getting Index for an Index Title:
```swift
let sectionIndexTitle = "Apple"
let sectionForSectionIndexTitle: Int? = (0 ..< monitor.numberOfSections())
    .lazy
    .map({ monitor.sectionInfoAtIndex($0) })
    .indexOf({ $0.indexTitle == sectionIndexTitle })
```

**Comment by JohnEstropia** [comment]
@markkrenek The workaround I posted a while ago is WRONG, sorry about that. I forgot that section indexes are independent of the sections themselves. Anyway you can access these methods from `ListMonitor` now:

```swift
public func sectionIndexTitles() -> [String]
public func targetSectionForSectionIndex(title title: String, index: Int) -> Int
```

See https://github.com/JohnEstropia/CoreStore/commit/71c3abc4f31241e9ab95b639071cfeaacb253489 for details.

**Comment by markkrenek** [comment]
Works great. Thanks John. I've just started experimenting with this library, and so far it is great.

**Comment by JohnEstropia** [comment]
@markkrenek Glad it works :) Thanks for the feedback!
