### ISSUE TITLE
where clause for one to many relationship 

### ISSUE THREAD

**Issue by seanliu1** [JohnEstropia/CoreStore#321]
I am looking for something similar to [NSPredicate predicateWithFormat:@"person.children.@count > 0"]

I tried to use 
dataStack.fetchAll(From<person>().where(\person.children.count == 0)

but it will give error 
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value. 
I wonder what is the correct syntax for this case?

**Comment by JohnEstropia** [comment]
Sorry I haven't gotten to add this anywhere in the README yet, but this is the current syntax for it:
```swift
dataStack.fetchAll(
    From().where((\.person ~ \.children).count() == 0)
)
```

**Comment by seanliu1** [comment]
Thanks, I actually already figure out but not as elegant as yours. 

I was using where(format: "children.@count == 0")  it also works, but it wont do any compile time for your.

**Comment by Vertuals** [comment]
what if we want a child from the list with a particular id ?

**Comment by JohnEstropia** [comment]
@Vertuals Sorry, there are no syntax sugars for them in CoreStore yet, but you can use the [`ANY` and `ALL`](https://stackoverflow.com/questions/30076452/difference-between-all-any-and-some-operators-in-nspredicate) operators in your own `NSPredicate`  and pass it to the CoreStore `where()` clause
