### ISSUE TITLE
Observing Managed Objects with Relationships

### ISSUE THREAD

**Issue by damianstrain** [JohnEstropia/CoreStore#324]
Hi John,

A quick question on Object/ListMonitors if you have time 😄 . If I fetch an Entity that has a one-to-many relationship for example, would adding to or updating that relationship in any way trigger a change event?

Many Thanks

**Comment by JohnEstropia** [comment]
@damianstrain Sorry for the late response. Adding and removing relationships will trigger the change event, but updates will not (the reference itself wouldn't change)

**Comment by damianstrain** [comment]
Thanks @JohnEstropia 👍
