### ISSUE TITLE
Cannot create an SQL store with a nil URL

### ISSUE THREAD

**Issue by seanliu1** [JohnEstropia/CoreStore#325]
This is my interface looks like 
```
    init <T: StorageInterface>(storage: T, persistenceManager: MediaPersistenceManager) {
        do {
            try dataStack.addStorageAndWait(storage)
        } catch {
            Logger.shared.log(error: error, message: "Failed to setup CoreData")
        }
}
```

I want to do dependency injection, then for test, I can provide in-memory storage, in production app I can use local storage. 

However I start to see once I change it to that way
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot create an SQL store with a nil URL.

It looks like  we always pass nil to finalURL if it comes from StorageInterface, should we have factory method based on input type to determine which constructor to use? 

```
 _ = try self.createPersistentStoreFromStorage(
                    storage,
                    finalURL: nil,
                    finalStoreOptions: storage.storeOptions
```

**Comment by JohnEstropia** [comment]
Use `<T: LocalStorage>` instead of `<T: StorageInterface>`

**Comment by seanliu1** [comment]
how to pass InMemoryStore if we wanna to use in memory storage for testing?

**Comment by JohnEstropia** [comment]
I see. If you need both then you need to implement the overloads for both.
```swift
init<T: StorageInterface>(...)
init<T: LocalStorage>(...)
```
