### ISSUE TITLE
Can we have async inside datastack.perform(asynchronous)

### ISSUE THREAD

**Issue by seanliu1** [JohnEstropia/CoreStore#327]
I would like to make network request inside dataStack.perform. Should we make network request  sync so that it can still work.

```
 self.dataStack.perform(asynchronous: { (transaction) in
            let item = transaction.fetchOne(<Item>())
            item.age = 5
           // fetch id
            URLSession.shared.dataTask(){ 
                 item.id = id 
           }, completionBlock:{  
  })
```

**Comment by JohnEstropia** [comment]
No, you can either do your transaction only after the network request completes, or do 2 separate transactions for before and after the request
