### ISSUE TITLE
Errors while adding as a SwiftPackage in Xcode 11 beta on MacOs 10.15

### ISSUE THREAD

**Issue by darek** [JohnEstropia/CoreStore#328]
Adding library as a Swift Package works well, but when i tried to build project (even without using library in code) 3 errors appear. Deployment is set to iOS 13, and Swift version to 5.

- **/SourcePackages/checkouts/CoreStore/Sources/CoreStoreSchema.swift:463:39: 'uniquenessConstraints' is only available in iOS 9.0 or newer**

- **/SourcePackages/checkouts/CoreStore/Sources/CoreStore+CustomDebugStringConvertible.swift:1209:56: 'uniquenessConstraints' is only available in iOS 9.0 or newer**

- **/SmartInventory-bcxwvpbuikyfdpbncadpveegmjff/SourcePackages/checkouts/CoreStore/Sources/DataStack+Migration.swift:573:38: 'startMigrationForStorage(_:sourceModel:destinationModel:mappingModel:migrationType:progress:)' is only available in iOS 10.0 or newer**

**Comment by jagbryrmiginte** [comment]
Ran into the same problem. The problem is a missing definition of the minimum deployment target in the Package.swift file. I've forked the current master and fixed this. You can use https://github.com/jagbryrmiginte/CoreStore until @JohnEstropia fixes this in the main repo.

**Comment by JohnEstropia** [comment]
@jagbryrmiginte Thanks for trying out a fix. Would you like to make a PR into the main repo's develop branch from your fork?

**Comment by jagbryrmiginte** [comment]
@JohnEstropia Done :)

**Comment by darek** [comment]
Works well, thanks
