### ISSUE TITLE
'CoreStore/CoreStore-Swift.h' file not found

### ISSUE THREAD

**Issue by puelocesar** [JohnEstropia/CoreStore#333]
I'm getting this error right after installing CoreStore via CocoaPods:

`/Users/ferreira/Projects/rpsn/ios/Pods/CoreStore/Sources/CoreStoreBridge.m:29:9: 'CoreStore/CoreStore-Swift.h' file not found`

CoreStore version is 6.3.1
Xcode version is 10.3 (10G8)
cocoapods version is 1.7.2

Since I don't need ObjC support, It works if I just remove CoreStoreBridge.m and CoreStoreBridge.h from the target, but then my CI server will break because I don't put my Pods folder on git

**Comment by JohnEstropia** [comment]
Hi, do you still have this issue?

**Comment by puelocesar** [comment]
Sorry, I cannot retest this because I'm not using CS on this project. I'll reopen if I rerun into this issue.

**Comment by rubenspessoa** [comment]
I'm having the same issue when I install CoreStore via cocoapods.

```'CoreStore/CoreStore-Swift.h' file not found```

Versions: 
CoreStore ~> 7.0.1
XCode ~> 11.3.1 (11C504)
Cocoapods ~> 1.8.3

Until now I couldn't find any workaround, but I noticed that there's no `CoreStore-Swift.h` file in the lib. 🤔

**Comment by rubenspessoa** [comment]
As stated in the issue #363, the solution is to add `use_frameworks!` in the Podfile. Since the CoreStore has some obj-c code in it, we should use frameworks instead of static libraries.
