### ISSUE TITLE
Calling QueryAttributes With Aggregate Count On One-To-Many Relationship

### ISSUE THREAD

**Issue by damianstrain** [JohnEstropia/CoreStore#334]
Hi John,

I'm executing the following (where `"boards"` is a one-to-many relationship on `Project`):

```swift
try CoreStore.queryAttributes(
    From<Project>(),
    Select("id", "key", "name", "createdOn", "updatedOn", .count("boards", as: "boardCount"))
)
```

Only the following attributes seem to be returned: `"id", "key", "name", "createdOn", "updatedOn"` and there are no exceptions or errors present.

I know that Project has 2 Boards, so I was expecting `"boardCount"` to be 2. 
Is what I'm doing valid? Can you call `.count` on a one-to-many relationship?

Many Thanks

**Comment by JohnEstropia** [comment]
@damianstrain Sorry for the long wait. The count operator here is a collection operator, which means it will count a value for a property if you use the `GroupBy` clause as well. Instead, can you try

```swift
Select("id", "key", "name", "createdOn", "updatedOn", .attribute("boards.@count", as: "boardCount")))
```

**Comment by damianstrain** [comment]
Excellent! Thanks @JohnEstropia
