### ISSUE TITLE
CoreStore.monitorSectionedList ordering issue.

### ISSUE THREAD

**Issue by matrosovDev** [JohnEstropia/CoreStore#337]
Need your help! Can you please comment on this [question](https://stackoverflow.com/questions/57515496/swift-corestore-ordering-list-monitor-issue)

**Comment by JohnEstropia** [comment]
https://stackoverflow.com/questions/57515496/swift-corestore-ordering-list-monitor-issue/57538668#57538668

**Comment by matrosovDev** [comment]
the question is answered by John [here](https://stackoverflow.com/questions/57515496/swift-corestore-ordering-list-monitor-issue/57538668#57538668):

Just want to post it here as well. If you have cities and states as in my example and you want to listen to cities updates which are sectioned by states, you need to .orderBy states names and also .orderBy cities name not just cities then you will see ordering in the section instead of all ordering through all section. This code work for me:

```
self.monitor = CoreStore.monitorSectionedList(
                From<ListEntityType>()
                    .sectionBy(#keyPath(ListEntityType.state.name))
                    .orderBy(.ascending(#keyPath(ListEntityType.state.name)), .ascending(\.name))
            )

```
Thanks @JohnEstropia =)
