### ISSUE TITLE
CoreStore monitorSectionedList multiple predicate

### ISSUE THREAD

**Issue by matrosovDev** [JohnEstropia/CoreStore#339]
Hi @JohnEstropia, can you please comment on this [question](https://stackoverflow.com/questions/57731824/corestore-sectioned-list-monitor-how-to-specify-where-clause-in-runtime), need your help one more time.

Thanks again!

**Comment by JohnEstropia** [comment]
Looks like your question was answered over at stackoverflow. Let me know if you have further questions 👍
