### ISSUE TITLE
UTF16 (Swedish grapheme cluster) issues

### ISSUE THREAD

**Issue by rivera-ernesto** [JohnEstropia/CoreStore#349]
I have described this issue here https://stackoverflow.com/q/58660170/1049134

Basically I store an `identifier` string with UTF16 Swedish characters:

`"/EXTERNAL/Gemensam RUN/FileCloud Test/Test folder åäö/Test with Swedish characters - åäö.xlsx"`

Which then don't match a fetch:

`CoreStore.fetchOne(From<Record>().where(\.identifier == identifier)) // Fails`

**Comment by JohnEstropia** [comment]
What type is `identifier` ?

**Comment by JohnEstropia** [comment]
Also, what happens if you use `NSPredicate` instead?
```swift
CoreStore.fetchOne(
    From<Record>().where(NSPredicate(format: "%K == %@", #keyPath(Record.identifier), identifier))
) 
```

**Comment by rivera-ernesto** [comment]
`identifier` is a Swift string. Found the problem and updated the StackOverflow issue.

In short I had two `identifier` instances with Swedish characters that are written with different grapheme clusters, so two binary different but both valid representations of the same String.
They are considered equal by Swift but for Core Data (and I guess because of SQLite under it) they are not considered equal, so they don't match the predicate.

It's not a problem of encoding, as both representations are in the same encoding, is a problem of grapheme clusters being valid in more than one way, and no way to "normalize" them that I could find.

Again refer to https://stackoverflow.com/q/58660170/1049134 if you are interested to know more.

**Comment by JohnEstropia** [comment]
@rivera-ernesto I see. If that's the case I'm not sure this is something that should be "fixed" at the library level. Here are some common practices for such cases:
1. Store a canonical string for you actual property value and use the same transformation for your search strings (See: [example1](https://stackoverflow.com/questions/17418443/normalize-or-canonicalize-string-for-core-data), [example2](https://stackoverflow.com/questions/16741632/how-to-properly-convert-to-a-canonical-string-for-searching-in-cocoa))
2. Try diacritic-insensitive query operators:
```swift
.where(format: "%K CONTAINS[cd] %@", #keyPath(Record.identifier), identifier)
```
