### ISSUE TITLE
Fetching on my background queue.

### ISSUE THREAD

**Issue by wickyou23** [JohnEstropia/CoreStore#356]
Hi, Team

Can I use the code below to get objects from my background queue and using those objects within the main queue?. Because sometimes I got some crash "EXE_BAD_ACCESS" when reading object properties.

<img width="720" alt="Screen Shot 2019-12-26 at 5 44 05 PM" src="https://user-images.githubusercontent.com/5183190/71472937-89342700-2807-11ea-84d5-59942c5ce901.png">

**Comment by JohnEstropia** [comment]
What exact error are you getting? Try to place an exception breakpoint and let me know where it stops

**Comment by wickyou23** [comment]
I don't have any more questions. I will close this topic.
