### ISSUE TITLE
CoreStore/CoreStore-Swift.h' file not found

### ISSUE THREAD

**Issue by rubenspessoa** [JohnEstropia/CoreStore#363]
Linked to this [issue](https://github.com/JohnEstropia/CoreStore/issues/333)

I'm having the same issue when I install CoreStore via cocoapods.

```'CoreStore/CoreStore-Swift.h' file not found```

Versions: 
CoreStore ~> 7.0.1
XCode ~> 11.3.1 (11C504)
Cocoapods ~> 1.8.3

Until now I couldn't find any workaround, but I noticed that there's no `CoreStore-Swift.h` file in the lib. 🤔

**Comment by rubenspessoa** [comment]
The solution is to add `use_frameworks!` in the Podfile. Since the CoreStore has some obj-c code in it, we should use frameworks instead of static libraries. I believe this information would be a great addition to the documentation @JohnEstropia . 

Happy coding!

**Comment by JohnEstropia** [comment]
I see, thanks for the heads up! Glad it was sorted out 👍

**Comment by skytoup** [comment]
Sometimes Cocoapods use static libraries to manage third-party libraries, maybe it would be better to make them import compatible.

```
#if canImport
#import <CoreStore/CoreStore-Swift.h>
#else
#import <CoreStore-Swift.h>
#endif
```
