### ISSUE TITLE
CoreStore 7.0.3 no longer compiles for watchOS

### ISSUE THREAD

**Issue by scogeo** [JohnEstropia/CoreStore#368]
The 6.0.3 release no longer compiles for the watchOS target using Xcode 11.3.1.   There are multiple errors related to the inclusion of `DiffableDataSource`.  For example:

> CoreStore/Sources/Internals.DiffableDataUIDispatcher.swift:55:28: error: use of undeclared type 'DiffableDataSource'
>         func purge<Target: DiffableDataSource.Target>(
>                            ^~~~~~~~~~~~~~~~~~

Seems to be missing some conditional compilation in a few files to get it compiling again, but don't have time to investigate at the moment, so reverting to 6.0.2.

**Comment by JohnEstropia** [comment]
I assume you meant 7.0.3? I'll push a fix, thanks!

**Comment by JohnEstropia** [comment]
Should be fixed in 7.0.4 now, let me know if you still have issues.

**Comment by scogeo** [comment]
Yeah sorry meant 7.0.3. Thanks for the quick fix will give it a try

**Comment by scogeo** [comment]
I verified 7.0.4 builds for me now on watchOS.
