### ISSUE TITLE
[Question] is Async Transaction is thread safe? 

### ISSUE THREAD

**Issue by seanliu1** [JohnEstropia/CoreStore#369]
I have a question regarding perform async function, I looked into the source code, but still not very clear for me. Here are code samples.

```
  group.enter()
  dataStack.perform(asynchronous: {(transaction) in 
        var p = transaction.create(Into<Person>())
        p.id = 1
        p.name = "test"
   }, completion {
        group.leave() 
  }

  group.enter()
   dataStack.perform(asynchronous: {(transaction) in 
        var p = try transaction.fetchOne(From<Person>().where(\Person.id == Int64(1))
        // can we guarantee we can read P from the previous insertion 
   }, completion {
        group.leave() 
  }
```
in the second group.enter, if we fetchOne, can we get the object we just inserted.

**Comment by JohnEstropia** [comment]
No, you can't. As the method name suggests, that is an asynchronous transaction. In fact, transactions run a serial asynchronous queue, so you don't really need your `DispatchGroup` there.

You can fetch the first created `Person` from inside the first transaction's `completion`, and also from inside the second transaction's `asynchronous` closure.

**Comment by seanliu1** [comment]
Thanks, sorry I mean in the second transaction's async closure.
