### ISSUE TITLE
Build failure with Xcode 11.4 beta

### ISSUE THREAD

**Issue by zachwaugh** [JohnEstropia/CoreStore#373]
My build is failing with Xcode 11.4 beta 2 and beta 3 using Carthage. Trying from master, I can see it's also failing to build with Xcode directly as well. All the failures are related to using `Self` in `KeyPathGenericBindings.swift`. Looks like an easy enough fix to replace `Self` with the concrete type. Happy to submit a PR if that's the correct fix.

<img width="882" alt="Screen Shot 2020-03-04 at 10 12 56 AM" src="https://user-images.githubusercontent.com/21447/75893517-ec8e9680-5e00-11ea-8eb9-8c51532e17e6.png">

**Comment by JohnEstropia** [comment]
Thank you. The Swift 5.2/Xcode 11.4 beta support branch is currently at `prototype/propertyWrapperFields`

I will move this to `develop`/`master` once the Xcode 11.4 GM candidate is released.

**Comment by Bengua27** [comment]
Hello,

Xcode 11.4 has been released. When are you planing to merge it to master?

Thanks a lot in advance,

**Comment by llKoull** [comment]
Hello @JohnEstropia  

Same problem here with Xcode 11.4 :S

**Comment by pingusNikalex** [comment]
please update pod's to support new Xcode version 11.4

**Comment by JohnEstropia** [comment]
I'm working on the documents today before pushing to master. If you need to test urgently please use the `prototype/propertyWrapperFields` branch for now:
```
pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'prototype/propertyWrapperFields'
```

**Comment by llKoull** [comment]
Great! Thanks!!!

**Comment by JohnEstropia** [comment]
The update is now in `develop` branch. Still making last-minute documentations before pushing to master, but feel free to update your dependency to
```
pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'develop'
```

**Comment by JohnEstropia** [comment]
Updated now for version `7.1.0`!
Please check the release notes: https://github.com/JohnEstropia/CoreStore/releases/tag/7.1.0

**Comment by llKoull** [comment]
YEAH! Thanks!!
