### ISSUE TITLE
Correct way to combine where clauses?

### ISSUE THREAD

**Issue by zachwaugh** [JohnEstropia/CoreStore#380]
I'm wondering the best way to build a query with conditionals. It looks something like this where we optional want to limit the query based on some state.

```swift
var query = From<Post>()

if unseen {
  query = query.where(\.unread == true)
}

if let date = updatedSince {
  query = query.where(\.updatedAt > date)
}
```

That will do an `OR`, but I want it to be an `AND`. The closest I've found is doing this:

```swift
var query = From<Post>()
var filter = Where<Post>()

if unseen {
   filter = filter && Where(\.unread == true)
}

if let date = updatedSince {
  filter = filter && Where(\.updatedAt > date)
}

query.where(filter)
```

That seems to work, but feels like maybe I'm missing a simpler way? Also, this is a contrived example, but I'd like to be able to pass in an existing `FetchChainBuilder<Post>` from elsewhere and append `Where` clauses using `AND` as well. Ideally, we'd have an API like:

```swift
func filter(query: FetchChainBuilder<Post>) -> FetchChainBuilder<Post> {
  var filters: [Where<Post>()] = []

  if unseen {
    filters.append(Where(\.unread == true))
  }

  if let date = updatedSince {
    filters.append(Where(\.updatedAt > date))
  }

  return query.where(filters)
}
```

Thanks!

**Comment by JohnEstropia** [comment]
You can use an array of `Where` clauses:
```swift
var filters: [Where<Post>] = []
if unseen {
    filters.append(\.unread == true)
}
if let date = updatedSince {
    filters.append(\.updatedAt > date)
}
return query.where(fitlers.combinedByAnd())
```

**Comment by zachwaugh** [comment]
Wow, that’s exactly what I was looking for, not sure I how I missed it. Thank you!
