### ISSUE TITLE
Question about migration

### ISSUE THREAD

**Issue by virulentum** [JohnEstropia/CoreStore#384]
Is there any way to perform two migrations at once: first a lightweight one and second a heavyweight one? 
For example, I have only three models in an app: "Model V1", "Model V20", "Model V21".
Current version of database may be different (V10, V11, ..., V20)
I would like to make migration from current to V20 (lightweight) and after that make migration from V20 to V21 (heavyweight).
I can do that in two step by adding two storages, but I would like to do it at once
Could you help me to solve this problem?

**Comment by JohnEstropia** [comment]
Not with the built-in methods. Tracking the versioning for such cases means your app needs to manage the version data somewhere else, so you will have to write one yourself.

**Comment by virulentum** [comment]
So, it means that I cannot do something like:
`let sqlStore = SQLiteStore(fileURL: url, migrationMappingProviders: [ mappingProvider1, mappingProvider2 ])`
where `mappingProvider1` for lightweight migration and `mappingProvider2` for heavyweight migration.
Is it true?

**Comment by JohnEstropia** [comment]
@virulentum Sorry, I think I misunderstood what you were trying to do.
If you are just trying to mix light and heavy migrations as part of the `MigrationChain` steps, then yes, the `migrationMappingProviders` will let you do that.

**Comment by virulentum** [comment]
@JohnEstropia,  well, it sounds good, but I have trouble with creating lightweight mapping provider, because I have only models V1, V20 and V21. How can I inform CoreStore, that a mapping provider is for a lightweight migration?

**Comment by JohnEstropia** [comment]
@virulentum As long as the `migrationChain` parameter of the `DataStack` initializer contains the mapping for each step in the progressive migration, anything not explicitly included in the storage `migrationMappingProviders` will automatically attempt to use lightweight migration.

**Comment by JohnEstropia** [comment]
See: https://github.com/JohnEstropia/CoreStore#custom-migrations
> For version migrations present in the `DataStack`'s `MigrationChain` but not handled by any of the `SQLiteStore`'s `migrationMappingProviders` array, CoreStore will automatically try to use `InferredSchemaMappingProvider` as fallback

**Comment by virulentum** [comment]
@JohnEstropia thank you very much for your answer!
