### ISSUE TITLE
SwiftUI Examples

### ISSUE THREAD

**Issue by kriszabala** [JohnEstropia/CoreStore#386]
The documentation indicates the new ListPublisher and ObjectPublisher support SwiftUI. Are there any examples of this such as a ListPublisher populating a List view?

**Comment by JohnEstropia** [comment]
@kriszabala Check out *SwiftUIView.swift* in the CoreStoreDemo app. You can play with this demo by running the CoreStoreDemo app and choosing the "Colors" demo from the menu.
