### ISSUE TITLE
CoreStoreObject as struct?

### ISSUE THREAD

**Issue by shift00** [JohnEstropia/CoreStore#392]
Hi,
I need some help.
I want to operate with many objects from the database, for example (by steps):
- save 100 objects as [MyDataModel],
- read last 50 MyDataModel objects from the database,
- change some property in each MyDataModel,
- remove previously sent 50 MyDataModel objects from the database.

My problem is that MyDataModel inherits from CoreStoreObject and can't be structurally. After the stress test (saving 200+ objects in DB and sending (read/edit/delete) 400+ objects from DB in 1s) I have huge memory load. 

Did anyone have a problem with dumping used entities?

**Comment by Saklad5** [comment]
Model objects are fundamentally reference types rather than value types, as they _reference_ an object in a context.

That isn’t the cause of the memory issue, though: you should make sure you aren’t referencing the objects after they are no longer needed.

**Comment by shift00** [comment]
Solved.
