### ISSUE TITLE
Q. Does versionLock have random number?

### ISSUE THREAD

**Issue by oddukgi** [JohnEstropia/CoreStore#398]
Hello? Thank you making good library.
I don't understand of versionLock. 
I made random number and put on code.

**Comment by JohnEstropia** [comment]
It’s a hash of your schema generated by Core Data, so you can’t put arbitrary values in it. You need to remove the versionLock argument for now then run your app once. From the debugger console you will see a printout of the actual versionLock values you need to use.

See: https://github.com/JohnEstropia/CoreStore#versionlocks

**Comment by oddukgi** [comment]
Thanks! I resolved issue 🌈
<img width="605" alt="versionLock_screenshot" src="https://user-images.githubusercontent.com/3068049/90850078-bbecea00-e3ab-11ea-84ce-f64586665c80.png">
