### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by sdgandhi** [JohnEstropia/CoreStore#4]
Hi, awesome library!

Supporting Carthage is pretty easy: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by JohnEstropia** [comment]
I pushed to the master branch after I saw your issue but I didn't notice you made a pull rquest ahead, sorry... (it's early morning)

Anyway please try if Carthage works for you now. I'm not sure if Carthage needs git tags for its versioning but if it does, ill update the tags as well.
