### ISSUE TITLE
Are main context object properties automatically updated from transactions?

### ISSUE THREAD

**Issue by zachwaugh** [JohnEstropia/CoreStore#406]
In general, are properties of the read-only main context objects live updated? Assuming they are fetched initially from the main data stack and only accessed from the main thread with all changes done in transactions. Sorry if this is an obvious question, but I couldn't find a clear answer. Here's a simple example:

```swift
class Controller {
  // An individual message fetched from the main data stack
  let message = dataStack.fetchOne(From<Message>().where(\.id == 1))

  func update() {
    dataStack.perform(
      asynchronous: { transaction in
          // a property is updated in a transaction
          let message = transaction.edit(self.message)
          message.title = "Test"
      },
      completion: { _ in 
        self.didUpdate()
      }
    )
  }

  func didUpdate() {
    // This is after the transaction saved
    // will message.title == "Test"?
  }
}
```

From a quick test, it appears that the main dataStack properties are updated, but this comment indicates that would only be the case if there was an observer/monitor attached: https://github.com/JohnEstropia/CoreStore/issues/352#issuecomment-562797703. Hoping you can clear that up, thank you!

**Comment by JohnEstropia** [comment]
Objects in the main thread would get updated, eventually. What I meant in the comment you linked is that if you rely on the timing of the updates you should be using one of the Observers/Publishers otherwise you have no control when they get updated

**Comment by zachwaugh** [comment]
Perfect, thank you!
