### ISSUE TITLE
Add instructions on building and running CoreStoreDemo

### ISSUE THREAD

**Issue by fractious** [JohnEstropia/CoreStore#41]
I'm attempting to run the CoreStoreDemo app, but being a relatively new developer to the platform, with no experience of Carthage I'm struggling to run the app in the iOS simulator.

Having followed the [Carthage's Getting Started instructions](https://github.com/Carthage/Carthage), I managed to get from here:

<img width="1552" alt="screen shot 2016-01-22 at 12 13 01" src="https://cloud.githubusercontent.com/assets/5934/12510452/d9a431a6-c101-11e5-8cfc-aa7f762e3feb.png">

to here, by running a `carthage update`:

<img width="1552" alt="screen shot 2016-01-22 at 14 31 38" src="https://cloud.githubusercontent.com/assets/5934/12513335/4513619c-c115-11e5-831a-0b20df3827fa.png">

However I'm not sure what the next step as the carthage instructions seem to be geared towards initial set up.

Should I be replacing the Embedded Binaries, which are currently referencing files in `…/JohnEstropia/…`?

Instructions on how to build and run the demo would be much appreciated. Many thanks.

**Comment by JohnEstropia** [comment]
@fractious Sorry about this. The demo shouldn't need any instructions. Something's wrong when I ran Carthage on my machine so there're missing stuff when I committed. I'll get to it as soon as I can.

**Comment by fractious** [comment]
Thanks John, appreciated.

**Comment by JohnEstropia** [comment]
@fractious I pushed an update. Try the master branch if it works for you.

**Comment by fractious** [comment]
Cheers John, that fixed it.

I had to do a `carthage update` to pull down `GCDKit`, which might be worth mentioning in the README.

**Comment by JohnEstropia** [comment]
@fractious Will do that. Thanks for the heads up!
