### ISSUE TITLE
Clarify documentation around "required" inverse relationships

### ISSUE THREAD

**Issue by H2CO3** [JohnEstropia/CoreStore#413]
Hi, and thanks for making CoreStore!

The documentation says:

> All relationships are required to have an "inverse" relationship.

However, I was able to create a schema where some of the relationships do not have inverses, and this did not result in any compiler or runtime errors. What's the deal?

**Comment by JohnEstropia** [comment]
The runtime assertions will run when the Schema is passed to the DataStack initiaizer. Were you actually able to use your objects?

**Comment by H2CO3** [comment]
Yes, I was able to fill the `DataStack` with related objects, and I was able to use `fetchAll` to retrieve objects along with their children. I even made sure that no lazy loading is happening (I printed some leaf properties in order to trigger faulting).

**Comment by JohnEstropia** [comment]
@H2CO3 I just checked and the assertions are there. Are you running on `-O` optimized builds? Assertions don't run on release builds. Other than that you may be implementing your own `CoreStoreLogger` and missed implementing the `CoreStoreLogger.assert(...)` method.

**Comment by H2CO3** [comment]
Alright, I was indeed running a release build. That's it, thanks!
