### ISSUE TITLE
Usage of ListPublisher via Combine

### ISSUE THREAD

**Issue by askopin** [JohnEstropia/CoreStore#417]
Hi, I'm trying to subscribe on list updates using Combine (without swiftUI) and have some trouble:
Is there any way to force `ListPublisher` to emit its current state (aka snapshot) on subscribe?
Or at least request it manually?

**Comment by JohnEstropia** [comment]
@askopin `ListPublisher` has an `addObserver` method that you can use to emit publisher events.

I'm currently working on Combine utilities for CoreStore, but I can't make any promises on the release date for that so please write your own Publishers for now.

**Comment by JohnEstropia** [comment]
Marking this issue as an `enhancement`, so no need to close it for now 👍

**Comment by JohnEstropia** [comment]
`ListPublisher`'s Combine utilities are now available from the `ListPublisher.reactive` namespace
