### ISSUE TITLE
'NSKeyedUnarchiveFromData' should not be used to for un-archiving and will be removed in a future release

### ISSUE THREAD

**Issue by sebastien-tribu** [JohnEstropia/CoreStore#418]
Hi,

I recently herited a project for work which uses CoreStore. On launching the app on Simulator (but same warnings appear on device), the app will load data from using `fetchOne`, like so:

```
    func image(with id: String) throws -> Image? { // Image is autogenerated in Image+CoreDataClass.swift
        let image = try CoreStoreDefaults.dataStack.fetchOne(
            From<Image>()
                .where(\.id == id)
        )
        return image
    }
```

Here's the issue: every time that the data is loaded, a bunch of runtime warnings appear (i.e. one per loaded image in my use case.): 

```
[general] 'NSKeyedUnarchiveFromData' should not be used to for un-archiving and will be removed in a future release
[general] 'NSKeyedUnarchiveFromData' should not be used to for un-archiving and will be removed in a future release
[general] 'NSKeyedUnarchiveFromData' should not be used to for un-archiving and will be removed in a future release
...
```

1. According to [this stackoverflow question](https://stackoverflow.com/questions/64583182/how-to-determine-which-core-data-transformable-attribute-is-not-using-secure-cod), it could be caused by transformable attributes, but I don't even know where to start to debug this using CoreStore. How would you debug this in CoreStore?
2. Do you know in which curcumstances data could be "wrongly" saved in CoreStore causing these un-archiving warnings? (differentiating pre-iOS 14 and iOS-14, perhaps ?)

Thank you !

**Comment by JohnEstropia** [comment]
Hi, thanks for the feedback. The deprecations have been handled in the `develop` branch, so feel free to use that branch for now. I'm currently finalizing documentations for some new features and I'll push the official update to `master` when that's wrapped up.

**Comment by JohnEstropia** [comment]
I'd ask just in case, but do you have transformable attributes that implement custom transformers? If so then those transformers need to be updated in your side, and possibly to implement the proper migration for those data as well.

**Comment by sebastien-tribu** [comment]
Hard to tell right now but I do have a sense that this could be the case. I'll come back here if I can wrap my head around this piece of code. Thanks

**Comment by JohnEstropia** [comment]
If you have a .xcdatamodeld file in your project, you can look for any Transformable attribue and check if their `Transformer` or `Custom Class` is set in the model editor. If they are, you can search your project for classes or strings that match those names.

**Comment by sebastien-tribu** [comment]
Right that's what the StackOverflow question suggested, but there is no .xcdatamodeld file to be found 🤔 still searching

**Comment by JohnEstropia** [comment]
If you can't find xcdatamodeld files, it's likely your project uses `CoreStoreObject` subclasses instead. You can search for these and look for either `Value.Transformable` (classic syntax) or `@Field.Coded` (new syntax) properties

**Comment by sebastien-tribu** [comment]
Aha, I was mistaken, we do have a .xcdatamodel file ! I'll create a new model version to fix these warnings on our project.

Many thanks for your guidance @JohnEstropia

**Comment by JohnEstropia** [comment]
@sebastien-tribu I see. Just be sure to test your migrations because there is the possibility that the old encoded objects (which were encoded using the deprecated encoder) may not be compatible with the new secured archivers.

Good luck!
