### ISSUE TITLE
Xcode 7.3 beta 2 breaking changes

### ISSUE THREAD

**Issue by csotiriou** [JohnEstropia/CoreStore#42]
With the latest beta released yesterday, there are problems that render the library uncompilable.

`
/CoreStore/Importing Data/BaseDataTransaction+Importing.swift:124:47: Ambiguous use of 'init'
Data/BaseDataTransaction+Importing.swift:187:45: Ambiguous use of 'init'
CoreStoreLogger.swift:89:16: Use of unresolved identifier '_stdlib_getDemangledTypeName'
`

Any idea on how to fix?

**Comment by JohnEstropia** [comment]
@csotiriou Thanks for the bug report! I fixed this in the develop branch: https://github.com/JohnEstropia/CoreStore/commit/5137649b78cc615f737fe9efcdeccb90eeee7b09
