### ISSUE TITLE
Supporting static and dynamic linking in Swift package manifests

### ISSUE THREAD

**Issue by tackgyu** [JohnEstropia/CoreStore#432]
In its package manifests, supporting library types are specified as `static`:

https://github.com/JohnEstropia/CoreStore/blob/9cc616f7208d79c7879bef0b240c94d01b6c6509/Package.swift#L35

From documents Apple provides by unspecifying its type, Xcode can choose whether to link the library statically or dynamically (https://developer.apple.com/documentation/swift_packages/product/2878196-library), so CoreStore can support both linkage types? If so, I'd like to contribute.

**Comment by JohnEstropia** [comment]
@tackgyu Thank you for looking into it! I think it should be fine to remove it. Do you want to make the PR?

**Comment by tackgyu** [comment]
@JohnEstropia Sure, let me post it

**Comment by JohnEstropia** [comment]
merged to develop, thanks!
