### ISSUE TITLE
Strange errors when try to archive in Xcode 13.

### ISSUE THREAD

**Issue by Desmuz** [JohnEstropia/CoreStore#438]
![Screenshot 2021-09-22 at 11 48 36](https://user-images.githubusercontent.com/73358057/134285289-a418d918-b9cd-4723-99a2-9acf75b152f0.png)

**Comment by JohnEstropia** [comment]
@Desmuz Which version of CoreStore are you using? And how do you install CoreStore (Pod version, Carthage, etc)?

**Comment by Desmuz** [comment]
@JohnEstropia CoreStore installed by SPM
```
{
        "package": "CoreStore",
        "repositoryURL": "https://github.com/JohnEstropia/CoreStore",
        "state": {
          "branch": null,
          "revision": "a40df37192622b093321fc2003f4a5cbe3860ffb",
          "version": "7.3.1"
        }
      }
```

**Comment by JohnEstropia** [comment]
@Desmuz I see, thanks. I haven't published an official Swift 5.5 SPM release yet, so I apologize. For now, you can directly link to the `develop` branch as a workaround. I'll try to push a new version within the week.

**Comment by Desmuz** [comment]
OK. Thanks.

**Comment by JohnEstropia** [comment]
@Desmuz I just published a new version. Please try again and let me know if you still have issues

**Comment by JohnEstropia** [comment]
Closing this ticket for now. Let me know if there are issues and I'll reopen the ticket
