### ISSUE TITLE
How to observe fetchCount

### ISSUE THREAD

**Issue by Feuerwerk** [JohnEstropia/CoreStore#439]
Hi,

Is there a way in CoreStore to observe the number of records in a table the same way one can use List-/ObjectPublisher or Combine to observe the records itself? In my case i don't want to use the ListPublisher since i don't want to fetch all records when they change and count them. Or does ListSnapshot.count don't fetch all records?

**Comment by JohnEstropia** [comment]
ListSnapshot.count does rely on fetched arrays in order to count them. My suggestion would be to cache this count to one of your entities' property and observe that value instead.

**Comment by Feuerwerk** [comment]
Thanks for your help. :-)
