### ISSUE TITLE
Observing changes by a single transaction

### ISSUE THREAD

**Issue by fractious** [JohnEstropia/CoreStore#44]
Is there a way of compiling a changeset of CRUD operations that occurred within a given `transaction`? I see that `commit()` returns a `SaveResult` but that doesn't look to say much about the operations that occurred. Would it be difficult to extend `SaveResult` in this way?

Alternatively, is it possible to scope a ListMonitor to a transaction somehow?

Thanks.

**Comment by JohnEstropia** [comment]
@fractious Yup, I understand the need. I'm trying to implement automatic CoreSpotlight indexing and bookkeeping changesets is one of the requirements to make it work. Once I get it working I may expose the CRUD changes somewhere.

There's no working prototype yet but you can glimpse of the progress in the `_corespotlight-test` branch. In the `NSManagedObjectContext+CoreSpotlight.swift` file, I intend to twiddle with the
`insertedObjects:`, `updatedObjects`, and `deletedObjects` info from the context.

> Alternatively, is it possible to scope a ListMonitor to a transaction somehow?
It doesn't make sense with async and sync transactions (their context dies with the closure they run in), but we can allow `UnsafeDataTransaction` to create their own ListMonitors/ObjectMonitors. I'm not sure if it will help your requirements right now but it seems simple and sensible enough to implement.

**Comment by fractious** [comment]
Yeah that sounds very helpful, I look forward to it.

**Comment by JohnEstropia** [comment]
Check out the utilities I added here: https://github.com/JohnEstropia/CoreStore/commit/def105e73a09f47e6a7855c392970c92c50778e8

If there's anything else feel free to ask anytime!

**Comment by fractious** [comment]
Sweet, they look good - are they methods on the `transaction` object?

**Comment by JohnEstropia** [comment]
Yes, so you will need to get the object references before you call `commit()`. Transaction fetching rules apply, so if you need to access those objects you'll need to use `fetchExisting()`:
```swift
CoreStore.beginAsynchronous { transaction in
    // ...
    let insertedObjects = transaction.insertedObjects(YourEntity) // Set<YourEntity>
    transaction.commit { result in
        if result {
            let insertedObjects = CoreStore.fetchExisting(insertedObjects) // [YourEntity]
            // ...
        }
    }
}
```

**Comment by fractious** [comment]
Cheers John, I'll give it a try on the next release. Thanks!
