### ISSUE TITLE
Archive project results in CoreStore errors

### ISSUE THREAD

**Issue by dtln820** [JohnEstropia/CoreStore#443]
While trying to archive my project, its results in errors from CoreStore. Running same project on device compiles successfully.
XCode: 13.1
CoreStore: 7.3.0
<img width="567" alt="Screen Shot 2021-11-05 at 3 38 46 PM" src="https://user-images.githubusercontent.com/25442606/140519235-49f6e320-2a3d-45bd-b514-bdfcbfb7d1c2.png">

Tried to clean build folder, to delete DerivedData, etc.

**Comment by Desmuz** [comment]
Same problem. Did you manage to fix it?

**Comment by JohnEstropia** [comment]
@dtln820 @Desmuz 
Xcode 13.1 compiles using Swift 5.5 so I recommend updating first to CoreStore 8.1.x.
Afterwards, let me know how it goes for you.

**Comment by Desmuz** [comment]
Everything works well, thanks.

**Comment by dtln820** [comment]
Yep, that works. But what if I need the old version? Should I just use another version of XCode?

**Comment by JohnEstropia** [comment]
@dtln820 Is there any reason you cannot update to the latest CoreStore version? I don't think there is any large migration work,just small syntax changes that the compiler would be able to point out for you.

**Comment by dtln820** [comment]
Unfortunately I use other pods that haven't been updated for some time, so after updating CoreStore - other pods resulted in compile errors.

**Comment by dtln820** [comment]
So yeah, anyway updating to CoreStore 8.1.x for XCode 13.1 solves the issues, thank you.
