### ISSUE TITLE
SQLite data lost when killing the app

### ISSUE THREAD

**Issue by odilebellerose** [JohnEstropia/CoreStore#450]
Hi,
when i create some objects by using 

```
dataStack.perform( asynchronous: { (transaction) -> StoredDocument? in) })
```
, everything is working well i can see datas in my sqlite database. However, when i kill my app, the database is empty. 

I've tried to save context on applicationWillTerminate but it doesn't change anything, 

```
do {
	try dataStack.unsafeContext().save()
} catch {
			
}
```

Any idea of what's happens ? 

Thanks you in advance for your answer.

**Comment by JohnEstropia** [comment]
Is the SQLite file URL constant or is it generated and somehow changes every launch?

The only reason CoreStore would reset a database is if the schema was updated AND the `.recreateStoreOnModelMismatch` option is set on the `SQLiteStore`

**Comment by odilebellerose** [comment]
I have a Singleton, with a start() func : 

```
open func start() {
	
		let store = SQLiteStore(fileName: "documents_storage.sqlite")
		
		do {
			try self.dataStack.addStorageAndWait(store)
		} catch {
			
		}
	}
```
and i'm calling this function in the AppDelegate : 

 ```
open func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
   DocumentStorageManager.shared.start()

return true
}
```

**Comment by odilebellerose** [comment]
> Are you using storyboards? If so you are likely accessing the `DataStack` before `addStorageAndWait()` returns. Storyboard initial ViewControllers get initialized before the `UIAppDelegate`'s `didFinishLaunching` is called. At least if I recall correctly.
> 
> Put a breakpoint on the `dataStack` getter and the `addStorageAndWait()` call and see if it's getting accessed somewhere else before the store is added.

I'm not using Storyboards and i tried to put breakpoints on functions using the dataStack it's seems ok. The `addStorageAndWait() `func seems to be called first.

**Comment by JohnEstropia** [comment]
How are you confirming the SQLite file contents? Are you sure the `perform()` methods are completing successfully?

**Comment by odilebellerose** [comment]
If i open the SQLite file in a browser i can see my records. In fact, i'm using CoreStore to store documents that i'm going to upload by using operation queue and background task. If i keep the app open or put it in the background, every thing is working well. That's why i can confirm SQLite file contents. If i kill the app and re-open it, my app should fetch documents in database and try to re-upload documents but they have been deleted.

**Comment by JohnEstropia** [comment]
After restarting the app, do you still see the records in the SQLite browser?

**Comment by odilebellerose** [comment]
No, i can't.

**Comment by JohnEstropia** [comment]
There's definitely something deleting your file (or a parent folder) somewhere. If you can isolate the issue in a shareable project I'll try to take a look.
