### ISSUE TITLE
Missing $ in README examples

### ISSUE THREAD

**Issue by idsky2** [JohnEstropia/CoreStore#453]
Your readme has
`let newPerson = dataStack.fetchOne(From<Person>.where(\.name == "John"))`
I'm just figuring out CoreStore but I think that should now be 
`let newPerson = dataStack.fetchOne(From<Person>.where(\.$name == "John"))`
otherwise I get an error that my class needs to inherit from NSManagedObject.

**Comment by JohnEstropia** [comment]
Thanks. Both syntaxes are correct depending if you're using `CoreStoreObject` or `NSManagedObject` subclasses. But since the rest of the README uses the propertyWrapper syntax, I'll try to make it more consistent.
