### ISSUE TITLE
Error while running application

### ISSUE THREAD

**Issue by Carmudii** [JohnEstropia/CoreStore#460]
Hello there I got some error when trying to running the application, any solution about this or patched version?

MacOS: 12.5
Xcode: 14.0
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)

<img width="1031" alt="Screen Shot 2022-09-16 at 08 16 56" src="https://user-images.githubusercontent.com/64249071/190535754-50e86c17-0bbf-4355-a79e-79afb262d52e.png">
<img width="1030" alt="Screen Shot 2022-09-16 at 08 22 16" src="https://user-images.githubusercontent.com/64249071/190536246-a6b43de8-c02e-40fc-8595-8cdb54b8d0ff.png">

**Comment by JohnEstropia** [comment]
Have you tried updating to CoreStore 9.0.0? It's the official supported version for Xcode 14/Swift 5.7

**Comment by Carmudii** [comment]
Thank you this solved now
