### ISSUE TITLE
Xcode 14 compile error

### ISSUE THREAD

**Issue by SMARTRAY-STUDIO** [JohnEstropia/CoreStore#461]
ForEach+SwiftUI.swift:65:40: error build: Key path value type 'NSManagedObjectID' cannot be converted to contextual type 'ID'

Xcode 14.0
SPM: CoreStore 8.1.0

**Comment by tkirby** [comment]
Update SPM to 9.0.0 for Xcode 14.0

**Comment by JohnEstropia** [comment]
Yes, @tkirby is right. In general, please check the supported CoreStore version whenever you update Xcode, especially if that Xcode version also uses a new Swift compiler version. Closing this ticket now.
