### ISSUE TITLE
XCODE 14.0 SUPPORT  REQUIRE

### ISSUE THREAD

**Issue by AbhimanyuForiOS** [JohnEstropia/CoreStore#462]
Dear owner and helpers ,
Please check the attached screenshot, I am facing an issue with CoreStore SPM when I switched to Xcode 14.0 in to `"ForEach+SwiftUI.swift"` file.
**Error** is : 

> `Key path value type 'NSManagedObjectID' cannot be converted to contextual type 'ID'`

<img width="1298" alt="Screenshot 2022-09-27 at 6 48 49 PM" src="https://user-images.githubusercontent.com/7630897/192538089-34220e08-e08c-4907-bbdc-a73aac5e2dfd.png">

Also please check another error : 

<img width="1257" alt="Screenshot 2022-09-27 at 6 56 23 PM" src="https://user-images.githubusercontent.com/7630897/192539207-7df5e291-7ed8-4ee6-9377-c0a569e81290.png">

<img width="521" alt="Screenshot 2022-09-27 at 6 57 31 PM" src="https://user-images.githubusercontent.com/7630897/192539268-74e68b48-cec6-4d7d-8871-51b1b5e73d97.png">

**Comment by LePips** [comment]
You need to update to CoreStore v9.0.0.

**Comment by JohnEstropia** [comment]
As mentioned, please upgrade to [9.0.0](https://github.com/JohnEstropia/CoreStore/releases/tag/9.0.0) if you need to use Xcode 14

**Comment by AbhimanyuForiOS** [comment]
thank you @JohnEstropia @LePips
