### ISSUE TITLE
Xcode 15 beta 4 - Command SwiftCompile failed with a nonzero exit code (build in SPM) version 9.0.0

### ISSUE THREAD

**Issue by maziar** [JohnEstropia/CoreStore#484]
![Screenshot 2023-07-23 at 3 03 12 PM](https://github.com/JohnEstropia/CoreStore/assets/60078/b0c306bb-607c-4d35-aa7c-3d2b6bfcdcef)

![Screenshot 2023-07-23 at 2 54 32 PM](https://github.com/JohnEstropia/CoreStore/assets/60078/f0c1b54b-04b5-42c9-9718-111bf3def803)

**Comment by JohnEstropia** [comment]
Can you target the `develop` branch for now and let me know if it works for you?

**Comment by TheNightmanCodeth** [comment]
@JohnEstropia just stopping by to say that the develop branch is building fine on latest Xcode 15 beta. Thanks!

**Comment by dosymbaev** [comment]
@JohnEstropia  when will this version be released? 🙌🏼

**Comment by maziar** [comment]
I changed it to "version": "9.1.0" and it solved
