### ISSUE TITLE
Plan to support Xcode 15?

### ISSUE THREAD

**Issue by KBog** [JohnEstropia/CoreStore#489]
Just wondering if there are plans to support Xcode 15 / iOS 17? The project doesn’t seem to compile.

**Comment by JohnEstropia** [comment]
Yes, it's currently in the `develop` branch. I've got my hands full this week and forgot to post a master release. Will publish soon, thanks for reminding!

**Comment by KBog** [comment]
Awesome, thank you as always!

**Comment by JohnEstropia** [comment]
Available now as `9.2.0`. Let me know if you have issues!

**Comment by KBog** [comment]
I will check it when I get back home (I’m out of town at the moment). I usually install using CocoaPods, would I be able to bump from 9.0.0 to 9.2.0? Because I only see 9.0.0 on CocoaPods.org. Thanks!

**Comment by KBog** [comment]
Everything worked, thank you!
