### ISSUE TITLE
`Where` clause missing `CONTAINS` comparison option

### ISSUE THREAD

**Issue by vovsyannikov** [JohnEstropia/CoreStore#506]
In my project there's a stored property with search info. What I would like to do is fetch all the objects that contains some searchable string. Right now the only way I see doing it is through unsafe `NSPredicate` where I can't even user `#keyPath(Document.searchInfo)` to alleviate some of the risks

```Swift
public func count(where predicate: Where<DBS.Document>, searchString: String? = nil) -> Int {
    do {
        var wholePredicate = predicate

        if let searchString, searchString.isEmpty == false {
            let searchPredicate = NSPredicate(format: "searchInfo CONTAINS %@", string)
            wholePredicate = wholePredicate && Where(searchPredicate)
        }
        
        let count = try transaction.fetchCount(
            From<DBS.Document>()
                .where(wholePredicate)
        )
        return count
    } catch {
        print("Error fetching document count: \(error.localizedDescription)")
        return 0
    }
}
```

Am I missing something or is it the only way of handling `CONTAINS` in CoreStore?

**Comment by JohnEstropia** [comment]
Yes, the type-syntax utilities are currently missing several predicate features. You can always write the raw String format for now, but as it is I'm still observing how the SwiftData utilities are evolving to see which ones we can hook up with CoreStore.

As always, if you have proposed implementations feel free to submit a PR.

**Comment by JohnEstropia** [comment]
Just a tip though, you can use `%K` so that you can still take advantage of `#keyPath`:
```swift
NSPredicate(format: "%K CONTAINS %@", #keyPath(Document.searchInfo), string)
```

**Comment by vovsyannikov** [comment]
> Just a tip though, you can use `%K` so that you can still take advantage of `#keyPath`:
> 
> ```swift
> NSPredicate(format: "%K CONTAINS %@", #keyPath(Document.searchInfo), string)
> ```

Yes I am aware of such method. However that's the problem: I get en error that `searchInfo` is not @objc marked. It's a `@Field.Stored` property so it seems that stringly typed `NSPredicate` is the only way out

**Comment by JohnEstropia** [comment]
Ah, I see. Sorry, I thought your model was using the `NSManagedObject` mode. For the `CoreStoreObject` subclasses, you can do this instead:
```swift
NSPredicate(format: "%K CONTAINS %@", String(keyPath: \Document.$searchInfo), string)
```

**Comment by vovsyannikov** [comment]
> Ah, I see. Sorry, I thought your model was using the `NSManagedObject` mode. For the `CoreStoreObject` subclasses, you can do this instead:
> 
> ```swift
> NSPredicate(format: "%K CONTAINS %@", String(keyPath: \Document.$searchInfo), string)
> ```

Oooh. That's neat. Thanks!
