### ISSUE TITLE
Xcode 16.0 beta 6 error - "'CATransaction' is unavailable in watchOS"

### ISSUE THREAD

**Issue by jmtiimo** [JohnEstropia/CoreStore#509]
I'm experiencing issues when trying to build the project using the latest `Xcode 16.0 beta 6 (16A5230g)`.
The error appears in the `Internals.DiffableDataUIDispatcher.swift` file. See image below.

Have anyone else experienced this issue? It worked perfectly in the `Xcode 15.4`. 

![Screenshot 2024-08-22 at 09 52 05](https://github.com/user-attachments/assets/5735e15d-cb78-4a6c-a247-78894ad810b8)

**Comment by DavidTiimo** [comment]
@jmtiimo I have made a PR for this.
