### ISSUE TITLE
The latest Demo App Does not compile 

### ISSUE THREAD

**Issue by praveencastelino** [JohnEstropia/CoreStore#57]
Xcode Version 7.3 (7D175)
Core Store version 1.6.1 [master branch]

Im getting following errors:
``
/<my_path>/github/CoreStore/CoreStoreDemo/CoreStoreDemo/Fetching and Querying Demo/QueryingResultsViewController.swift:23:29: error: use of unresolved identifier '_stdlib_getDemangledTypeName'
                    detail: _stdlib_getDemangledTypeName(item)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<my_path>/github/CoreStore/CoreStoreDemo/CoreStoreDemo/Fetching and Querying Demo/QueryingResultsViewController.swift:31:29: error: use of unresolved identifier '_stdlib_getDemangledTypeName'
                    detail: _stdlib_getDemangledTypeName(item)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
``

Also, there are few warnings related to swift
``
/<my_path>/github/CoreStore/CoreStoreDemo/CoreStoreDemo/Transactions` Demo/TransactionsDemoViewController.swift:63:83: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
        let longPressGesture = UILongPressGestureRecognizer(target: self, action: "longPressGestureRecognized:")
                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                  #selector(TransactionsDemoViewController.longPressGestureRecognized(_:))
/<my_path>/github/CoreStore/CoreStoreDemo/CoreStoreDemo/Transactions Demo/TransactionsDemoViewController.swift:71:21: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
            action: "refreshButtonTapped:"
                    ^~~~~~~~~~~~~~~~~~~~~~
                    #selector(TransactionsDemoViewController.refreshButtonTapped(_:))
``

**Comment by JohnEstropia** [comment]
@praveencastelino Oh my. Thanks!

**Comment by JohnEstropia** [comment]
@praveencastelino fixed now, thanks again!
