### ISSUE TITLE
Crash with implicitly unwrapped optional on a simple setup

### ISSUE THREAD

**Issue by rshev** [JohnEstropia/CoreStore#59]
I'm getting `fatal error: unexpectedly found nil while unwrapping an Optional value` on `fetchAll` in the following simple setup:
```
        do {
            try CoreStore.addSQLiteStoreAndWait()
            let users = CoreStore.fetchAll(From(User))
            print(users)
        }
        catch (let error) {
            print(error)
        }
```

Crash occurs in `entityNameForClass` func, and entity `User` clearly exists in the model.
What am I doing wrong?

PS. Maybe you shouldn't implicitly unwrap optional there at all? What if someone feeds wrong class?

**Comment by JohnEstropia** [comment]
@rshev Did you check if the `User` class is set correctly in your xcdatamodeld file? Note that the `Module` name matters.

You can inspect how your entities look like after calling `addSQLiteStoreAndWait()`:
```swift
try CoreStore.addSQLiteStoreAndWait()
print(CoreStore.entityTypesByName)
```

> PS. Maybe you shouldn't implicitly unwrap optional there at all? What if someone feeds wrong class?

Nobody should be able to perform operations on a wrong class (i.e. you shouldn't be fetching/creating a class that's not in your model), so catching this mistake early is best.

See the README file's entry on [Creating Objects](https://github.com/JohnEstropia/CoreStore#creating-objects) (yours is a fetch, but the same principles apply):
```
If the entity does not belong to any store, an assert will be triggered. This is a programmer error and should never occur in production code.
```
