### ISSUE TITLE
.beginAsynchronous will check for main thread

### ISSUE THREAD

**Issue by SteveKChiu** [JohnEstropia/CoreStore#6]
I am not sure why this assert is needed, as the code show it immediately jump to different queue.

This is what I am doing, I fetch json from server in different queue; upon completion I call .beginAsynchronous to start transaction to store the object, and at that time the queue is *NOT* main queue.

So my question is whether it is absolutely necessary to call .beginAsynchronous in the main thread? Or we can remove this assertion?

**Comment by JohnEstropia** [comment]
@SteveKChiu You're right, they are completely unnecessary and should be thread-safe without them. There's probably a couple more places where thread checks are overprotective, but I'll remove the ones from the `beginXXXX()` methods. Thanks!
