### ISSUE TITLE
Question:  'CoreStore was compiled with optimization' -- a crash

### ISSUE THREAD

**Issue by wm-j-ray** [JohnEstropia/CoreStore#70]
I must be doing something wrong.  After I get successful stack creation I am trying to insert a record and I am getting the following error and a crash: 

    CoreStore was compiled with optimization - stepping may behave oddly; variables may not be available

I'm not sure what this error means or what I'm doing wrong.  Any help would be appreciated and thanks in advance

The offending line is 67 in BaseDataTransaction.swift and here is my complete code.

            let dataStack = DataStack(modelName: "crashyApp")
        do {
            try dataStack.addSQLiteStoreAndWait(
                fileName: "crashyApp.sqlite",
                configuration: nil,
                resetStoreOnModelMismatch: true)
            print("Successfully created store")
            
        }
        catch {
            print("Failed creating store with error: \(error as NSError)")
        }

   
        dataStack.beginAsynchronous { (transaction) -> Void in
            let aNote = transaction.create(Into(NoteMO))
            aNote.content = "Note Five"
            aNote.dateCreated = NSDate()
            aNote.identifier = NSUUID().UUIDString
            
            
            
            transaction.commit { (result) -> Void in
                switch result {
                case .Success(let hasChanges): print("success!")
                case .Failure(let error): print(error)
                }
            }
        }

**Comment by JohnEstropia** [comment]
This has nothing to do with CoreStore, or your code for that matter. This is a problem that sometimes happen when you put a breakpoint in Xcode but the debugger can't read variable (for the debugger) due to optimizations. See http://stackoverflow.com/questions/32772573/project-name-was-compiled-with-optimization-stepping-may-behave-oddly-varia

The crash is just Xcode crashing, not your app.

**Comment by wm-j-ray** [comment]
Thanks John.
And thanks for all the hard work on CoreStore.
