### ISSUE TITLE
Possible Carthage Issue -  hung up on fetching CoreStore

### ISSUE THREAD

**Issue by wm-j-ray** [JohnEstropia/CoreStore#72]
I'm running Carthage 0.16.2 and for some reason terminal gets hung up on fetching CoreStore.  There is no issue with GCDKit.  This is new behavior in the last day or two.

    Here is my terminal input -> carthage update --platform iOS,Mac
    Here is the line from my cartfile -> github "JohnEstropia/CoreStore" >= 1.6.0

The IOS,Mac switch is there due to some issues in non CoreStore related frameworks.  With this switch CoreStore and GCDKit used to build.  

Any pointers appreciated and thanks in advance.

**Comment by JohnEstropia** [comment]
@wm-j-ray I'm so sorry, this is probably because I forgot to update the Cartfile when I updated to GCDKit 1.2.5. 

Fixed now in CoreStore 1.6.7. Tell me if it works for you

**Comment by wm-j-ray** [comment]
All better, thanx
