### ISSUE TITLE
Beta testers for the new ICloudStore

### ISSUE THREAD

**Issue by JohnEstropia** [JohnEstropia/CoreStore#73]
A prototype is already available in the current [CoreStore 2.0 develop branch](https://github.com/JohnEstropia/CoreStore/tree/corestore2_develop), but I currently have no project to test heavy iCloud functionality with.

If anyone is interested to try it out, I would appreciate any feedbacks and/or pull requests.

**Comment by pointspy** [comment]
Hello. I have problems using icloud storage. Could you show how to use this feature with my data model. Is there any sample code for this?

**Comment by pointspy** [comment]
And a huge thanks for the very handy library!

**Comment by JohnEstropia** [comment]
Hi, there is a sample in the [README](https://github.com/JohnEstropia/CoreStore#icloud-store). What problems are you encountering?

If you can join the [Slack group](http://swift-corestore-slack.herokuapp.com/) I'd be happy to discuss with you :)

**Comment by ruslanskorb** [comment]
I'll just leave it here - [Core Data iCloud Deprecation](https://developer.apple.com/library/content/releasenotes/General/WhatNewCoreData2016/ReleaseNotes.html#//apple_ref/doc/uid/TP40017342-CH1-DontLinkElementID_8).

**Comment by JohnEstropia** [comment]
I doubt if many apps this feature anyway 😄  (If anyone does, please do provide feedback)

I've had this implemented for several months now but have only heard from a couple of users about it. I might mark the `ICloudStorage` as deprecated in the near future.

**Comment by JohnEstropia** [comment]
I'm closing this issue as iCloud Core Data is being deprecated by Apple and iOS 11 is on its way. CoreStore will continue to support `CloudStorage` but I encourage users of these API to send in feedback. Thanks!
