### ISSUE TITLE
mergeChangesFromContextDidSaveNotification crash

### ISSUE THREAD

**Issue by tomasgibas** [JohnEstropia/CoreStore#74]
```swift
CoreStore.beginAsynchronous { (transaction) in
            let bookIds = Array(booksWithRating.keys).map { NumberFormatter.numberFromString($0)!.integerValue }
            let books = transaction.fetchAll(From(Book), Where(kBookWithIDsPredicate, bookIds))
            books?.forEach({ (book) in
                transaction.delete(book.rating)
                let rating = transaction.create(Into(Rating))
                rating.date = NSDate()
                rating.rating = Float(booksWithRating[String(format: "%@", book.bookId!)]!)
                book.rating = rating
            })
            transaction.commit()
        }
```
Most of the time, when it comes to commit, an exception will raise in NSManagedObjectContext+Setup.swift, line 97. Am I doing something wrong? I am not sure what.

**Comment by JohnEstropia** [comment]
What does the exception message say?

**Comment by tomasgibas** [comment]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Rating compare:]: unrecognized selector sent to instance 0x12823c5a0'

**Comment by JohnEstropia** [comment]
Somewhere in one of your observers, you are using a `Rating` instance incorrectly. Your hint is there:
```
 '-[Rating compare:]: unrecognized selector sent to instance
```

[Add an exception breakpoint](https://developer.apple.com/library/ios/recipes/xcode_help-breakpoint_navigator/articles/adding_an_exception_breakpoint.html) in Xcode and try to reproduce the crash. The breakpoint will stop at the real location of your problem.

This is not a CoreStore issue so I'm closing this ticket.
