### ISSUE TITLE
mainContext ? Can I access it?

### ISSUE THREAD

**Issue by wm-j-ray** [JohnEstropia/CoreStore#77]
John,

 I have a collection of predicates that I'd like to use to create NSFetchedResultsControllers.  I realize this is defeating a lot of the purpose of CoreStore, but nonetheless.  I've tried:

CoreStore.mainContext and CoreStore.defaultStack.mainContext

    lazy var fetchedResultsController: NSFetchedResultsController = {
    // Initialize Fetch Request
    let fetchRequest = NSFetchRequest(entityName: "Item")
     
    // Add Sort Descriptors
    let sortDescriptor = NSSortDescriptor(key: "createdAt", ascending: true)
    fetchRequest.sortDescriptors = [sortDescriptor]
     
    // Initialize Fetched Results Controller
    let fetchedResultsController = NSFetchedResultsController(fetchRequest: fetchRequest, managedObjectContext: self.managedObjectContext, sectionNameKeyPath: nil, cacheName: nil)
     
    // Configure Fetched Results Controller
    fetchedResultsController.delegate = self
     
    return fetchedResultsController
    }()

**Comment by JohnEstropia** [comment]
You can use `NSFetchedResultsController.createFor(...)` to create a CoreStore-managed controller:
```swift
let controller = NSFetchedResultsController.createFor(
    CoreStore.defaultStack,
    From(Item),
    OrderBy(.Ascending("createdAt"))
)
controller.delegate = self
return controller
```
If you have raw `NSPredicate` and `NSSortDescriptor`s,  `Where` clauses and `OrderBy` clauses accept them in their initializers
```swift
let controller = NSFetchedResultsController.createFor(
    CoreStore.defaultStack,
    From(Item),
    Where(yourPredicate),
    OrderBy(yourSortDescriptors)
)
```

**Comment by wm-j-ray** [comment]
Thanks John. I'm learning albeit slowly.

**Comment by JohnEstropia** [comment]
If you don't need an `NSFetchedResultsController` per se, I recommend you use `ListMonitor`s instead. They're much more type-safe and handles a lot of NSFetchedResultsController bugs, and they also support "multiple delegates".

**Comment by wm-j-ray** [comment]
I'm going to give it a shot. I want to start playing around with that DTTableManager library that abstracts out a lot of the lower level mechanics of tableviews and its just pure FRC. (At first blush).

I used to use TLIndexPathTools, very good but it's ObjC and I am trying to make the transition to Swift and get more toward a Clean Swift architecture.

Again, thanks so much for the help.

**Comment by JohnEstropia** [comment]
If you're app still have Objective-C code left you might want to play with CoreStore 2.0 (see corestore2_develop branch).

All CoreStore Swift types have their ObjectiveC counterparts (and bridgeable back and forth).

Just to give you more options :)

I'll close this issue for now. Feel free to ask anything else anytime!
