### ISSUE TITLE
Demo Request - Observers

### ISSUE THREAD

**Issue by wm-j-ray** [JohnEstropia/CoreStore#78]
John,

Do you have any sample code that illustrates deleting and (maybe) reordering tableViews

**Comment by JohnEstropia** [comment]
There's a [ListObserver demo](https://github.com/JohnEstropia/CoreStore/blob/master/CoreStoreDemo/CoreStoreDemo/List%20and%20Object%20Observers%20Demo/ListObserverDemoViewController.swift) in the Demo App. 

It handles inserts, deletes, updates, and moves. To simulate a "move", open the detail page for a color and drag the "hue" slider, which causes the cell in the UITableView to "move".
![observers](https://cloud.githubusercontent.com/assets/3029684/15766227/405e54c0-2977-11e6-9e7d-f0c68eea281f.gif)

**Comment by wm-j-ray** [comment]
Thanks John,

I've been looking at that demo and trying to get my head around it. I'll keep plugging along.
