### ISSUE TITLE
Cannot run Demo

### ISSUE THREAD

**Issue by harrisrap** [JohnEstropia/CoreStore#89]
I downloaded the zip.  Then I opened CoreStore.xcworkspace.  Then I tried compiling, and I get this error in ObjectMonitor.swift: No such module 'GCDKit'

**Comment by JohnEstropia** [comment]
Hi @harrisrap,
I recommend downloading CoreStore through git clone instead, so you can pull submodules (GCDKit) with it:
```
git clone --recursive https://github.com/JohnEstropia/CoreStore.git
```

**Comment by JohnEstropia** [comment]
I'll fix this on the Swift 3 branch so the project from the github zip download can still work.

Thanks for the feedback!

**Comment by JohnEstropia** [comment]
GCDKit dependency is dropped in CoreStore's Swift 3 support branch: `swift3_develop`.

For all other versions, please use git clone to pull submodules, or use Carthage.
