### ISSUE TITLE
Object-C beginAsynchronous crash

### ISSUE THREAD

**Issue by WilliamXueShao** [JohnEstropia/CoreStore#95]
[CSCoreStore beginAsynchronous:^(CSAsynchronousDataTransaction * _Nonnull transaction) {
                    [transaction commitWithCompletion:nil];
                }];
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CoreStore.CSBaseDataTransaction commitWithCompletion:]: unrecognized selector sent to instance 0x125ec6540'
*** First throw call stack:
(0x180e0edb0 0x180473f80 0x180e15c4c 0x180e12bec 0x180d10c5c 0x100102a64 0x100337204 0x1003371c0 0x1002f6fd0 0x1017f5634 0x100655358 0x100655398 0x10182fdf8 0x101825a3c 0x101832554 0x10182972c 0x101825a3c 0x101834c9c 0x101834364 0x180a71470 0x180a71020)
libc++abi.dylib: terminating with uncaught exception of type NSExceptio

**Comment by JohnEstropia** [comment]
I'm not sure why you're getting a `CSBaseDataTransaction` instance instead of a `CSAsynchronousDataTransaction`... Are you compiling with optimizations (`-O`) on?

**Comment by WilliamXueShao** [comment]
My  configuration Information was:
Bulid Settings -> Swift Compiler - Code Generation -> Optimization Level  Debug None [-Onone] and Release Fast [-O]
Bulid Settings -> Apple LLVM 7.1 - Code Generation -> Optimization Level  Debug None [-O0] and Release Fastest,Smallest[-Os]

I tested each optimization item, it still crash.

**Comment by JohnEstropia** [comment]
I'll investigate into this. Thanks for the report!

**Comment by JohnEstropia** [comment]
Fixed in version 2.0.6!
