### ISSUE TITLE
Errors With the latest version of Xcode and Swift 2.3

### ISSUE THREAD

**Issue by AleksandarPetrov** [JohnEstropia/CoreStore#97]
I have few errors with optionals when I'm trying to build the library with Xcode 8 and Swift 2.3. 

I've updated CoreStore to version 2.0.6. I've changed CoreStore target flag 'Use Legacy Swift Language Version' to YES (same with NO). I've also added 'developer_info' and 'post_install' to my pod file as it's shown [here](https://medium.com/@ziminalex/xcode-8-0-cocoapods-95d8e7a769a9#.h7qgulxm2). However errors are still there.

I ran out of ideas. Do I need swift 3 branch? Any suggestions?

**Comment by jamesbebbington** [comment]
@AleksandarPetrov it looks like there are some tweaks that need to be made to support Swift 2.3.

Hey @JohnEstropia, now that Xcode 8 GM has been released, is there any chance you could release a Swift 2.3 compatible version soon? CoreStore is now the only library that my app uses, that won't compile in Xcode 8. Many thanks.

**Comment by JohnEstropia** [comment]
I apologize for this. I'll try to prepare a separate branch for Swift 2.3 support within the day.
I can't update the master branch directly yet because Xcode 8 breaks iOS 7 support (which CoreStore still supports)

**Comment by jamesbebbington** [comment]
Thanks @JohnEstropia, much appreciated.

**Comment by JohnEstropia** [comment]
Aaaand I just learned that [Cocoapods still has Xcode 8 support in beta](https://github.com/CocoaPods/CocoaPods/issues/5825)...

Apologies for everyone waiting for this update, but it looks like I need another day to satisfy Cocoapods and Travis (iOS 8 simulator unit tests seem(?) broken...).

**Comment by jamesbebbington** [comment]
Thanks for the update @JohnEstropia, I hope Cocoapods doesn't cause you too much heartache. 

Relatedly, I used [this workaround](http://stackoverflow.com/questions/38446097/xcode-8-beta-3-use-legacy-swift-issue/38466703#38466703) to stop Xcode 8 complaining about the `SWIFT_VERSION`.

**Comment by JohnEstropia** [comment]
Swift 2.3/Xcode 8 support is now in the `master` branch, at version 2.1.0. You can install this through Cocoapods by using the Cocoapods RC build.

iOS 7 support is in a separate `master_ios_7_to_9` (I know..) branch

**Comment by jamesbebbington** [comment]
Perfect, thanks @JohnEstropia!
