### ISSUE TITLE
GCD issues in Xcode 8 with Swift 2.3

### ISSUE THREAD

**Issue by gauravstomar** [JohnEstropia/CoreStore#99]
❗ [CoreStore: Assertion Failure] BaseDataTransaction.swift:58 create
  ↪︎ Attempted to create an entity of type 'MediaMO' outside its designated queue.

**Comment by JohnEstropia** [comment]
Hi, can you show how your transaction is set up?

**Comment by gauravstomar** [comment]
CoreStore.beginAsynchronous { (transaction) -> Void in
    let media = transaction.create(Into(MediaMO))
    media.name = "Image.png"
    media.url = url
    transaction.commit()

    }

**Comment by JohnEstropia** [comment]
Hmm I can't find anything wrong with your code, but I can't reproduce this with the test cases and the demo app. Can you isolate the conditions to reproduce this assertion failure? If you can edit the demo app to reproduce this it would greatly help

**Comment by gauravstomar** [comment]
_Sure_

**Comment by gauravstomar** [comment]
Its even crashing while fetching records with same GCD issue 
                            ```
CoreStore.beginAsynchronous({ (transaction) in
                                var mediaMO: MediaMO!
                                mediaMO = CoreStore.fetchOne(From(MediaMO), Where("mediaId == \(fileId)"))
})
```

> ❗ [CoreStore: Assertion Failure] DataStack+Querying.swift:126 fetchOne
>   ↪︎ Attempted to fetch from a 'CoreStore.DataStack' outside the main thread.
>

**Comment by gauravstomar** [comment]
Surprisingly adding it main queue fix the same. Any help?

```
                            CoreStore.beginAsynchronous({ (transaction) in

                                var mediaMO: MediaMO!

                                dispatch_async(dispatch_get_main_queue()) {
                                    mediaMO = CoreStore.fetchOne(From(MediaMO), Where("mediaId == \(fileId)"))
                                }
})

```

**Comment by gauravstomar** [comment]
Same crashing for;
```
        guard let allClaimsData = CoreStore.fetchAll(From(MediaMO), Where("isSynced == %@", false)) else {
            return
        }

```
❗ [CoreStore: Assertion Failure] DataStack+Querying.swift:160 fetchAll
  ↪︎ Attempted to fetch from a 'CoreStore.DataStack' outside the main thread.

But it worked when adding 
```
        dispatch_async(dispatch_get_main_queue()) {
            guard let allClaimsData = CoreStore.fetchAll(From(ClaimsMO), Where("isSyncedChecklist == %@", false)) else {
                return
            }
        }
```
Any guesses?

**Comment by JohnEstropia** [comment]
That just means you're calling DataStack methods from background queues. DataStack methods should be called from the main queue. Check that your `CoreStore.begin***()`, `CoreStore.fetchAll()`, etc are called from the main queue.

**Comment by gauravstomar** [comment]
The same code was working fine for Swift 2.2, any catch?

**Comment by gauravstomar** [comment]
We are using the same since last 4 months, it was working like a charm. Its really a wonderful and hassle free Core Data wrapper but some how its crashing intermittently after migrating to Xcode 8/Swift 2.3

Its quite weird to add dispatch_async(dispatch_get_main_queue()) before each `CoreStore.begin***()`, `CoreStore.fetchAll()`, etc. There should be some kind of catch we are not getting :(

**Comment by JohnEstropia** [comment]
Can you try to add `assert(NSThread.isMainThread())` before your `CoreStore.begin...`, `CoreStore.fetch...` calls? If that assertion fails then all I can advise is to check why your methods are now running on a background thread (maybe you missed something during Swift 2.3 migration?)

**Comment by gauravstomar** [comment]
May be it will work; 
```
extension CoreStore {
    public static func beginAsynchronous(closure: (transaction: AsynchronousDataTransaction) -> Void) {
        dispatch_async(dispatch_get_main_queue()) {
            CoreStore.beginAsynchronous(closure)
        }
    }
}

```

**Comment by JohnEstropia** [comment]
I really suggest you investigate first why your methods are running on the background queue after migrating to Swift 2.3. CoreStore's `DataStack` methods had always checked for main thread execution, and if it's failing assertions now then that just means your code had an unintended change somewhere else. Can you send a stack trace from when you hit the assertion failure?

**Comment by JohnEstropia** [comment]
@gauravstomar Just to make sure, I need to know what happens if you put `assert(NSThread.isMainThread())` before calling beginAsync or fetchAll functions.
```swift
assert(NSThread.isMainThread())
CoreStore.beginAsynchronous({ (transaction) in
    // ...
}
```
```swift
assert(NSThread.isMainThread())
let objects = CoreStore.fetchAll( // ...
```

Please tell if the assert fails for you or not.

**Comment by gauravstomar** [comment]
It fails! It usually happens we user CoreStore with Alamofire

**Comment by JohnEstropia** [comment]
If the `assert(NSThread.isMainThread())` outside CoreStore fails, then you'll have make changes to your code so DataStack calls happen on the main thread. It seems you can tell Alamofire which queue run responses on. See https://github.com/Alamofire/Alamofire/issues/1319

**Comment by popwarfour** [comment]
cs_isCurrentExecutionContext() -> Bool.

Looks like DispatchQueue.getSpecific(key: Static.specificKey) is return nil.

I'm not familiar enough with GCD but is this expected behavior?

Line 63ish in DispatchQueue+CoreStore.swift, swift3_develop branch
